src/report.c
Resolves #18.  Switch proc.mem metric from counter to gauge.
=> (18) proc.mem is currently a counter, a gauge is desired.

.github/workflows/build.yml, cli/Makefile, cli/TODO, cli/cmd/dash.go, cli/cmd/events.go, cli/cmd/history.go, cli/cmd/metrics.go, cli/cmd/prune.go, cli/cmd/run.go, cli/cmd/util.go, cli/cmd/version.go, cli/events/events.go, cli/history/sessions.go, cli/history/sessions_test.go, cli/metrics/metric.go, cli/run/run_test.go, cli/run/scopeconfig.go, cli/run/scopeconfig_test.go, cli/util/newlinereader.go, cli/util/newlinereader_test.go, cli/util/util.go, install_build_tools.sh
* Closes #3: Should handle unknown characters in dashboard event output more
gracefully.
* Closes #8: Now returns event count after filtering, except for with JS
expressions.
* Closes #9: Q now exits dash.
* Closes #12: Help should now have consistent capitalization.
* Closes #7: Scope run now has more examples.
* Closes #4: Commands which fail validation now print help.
* Closes #1: Failed executions now prompt to clean empty session.
* Closes #19: Log Regex is now smarter about picking up log directories or
files.
* Closes #17: scope metrics -c no longer fails silently.
* Closed #23: rearranges scope dash to be more compact.
=> Fixes numerous issues.

src/ctl.c
=> (86) Stop sending null characters in console/log data.

website/src/pages/docs/cli-reference.md, website/src/pages/docs/community.md, website/src/pages/docs/how-works.md, website/src/pages/docs/installing.md, website/src/pages/docs/library-using.md, website/src/pages/docs/loader-library.md, website/src/pages/docs/overview.md, website/src/pages/docs/requirements.md, website/src/pages/docs/uninstalling.md, website/src/pages/docs/what-do-with-scope.md
- Rephrase "programming language" as "runtime-agnostic," at Dritan's & Ledion's request.
- Minor copy edits – mostly splitting or punctuating long sentences.
- Fix 1 malformed link, & 1 obsolete/mismatched link label.
=> Docs messaging & cleanup

website/src/data/community.yaml, website/src/data/header.yaml, website/src/data/readyGetStarted.yaml, website/src/pages/docs/community.md, website/src/pages/docs/quick-start-guide.md
Adding the UTM to see when community referrals come from Appscope.dev, and removing some of the direct links to Slack since it doesn't work even once you're joined to the community
=> Updating Community Links

website/src/pages/docs/installing.md
- This removes the old `io.cribl.cdn/dl/` download-directory reference.
=> Remove leftover download URL

cli/demo/scope.yml, conf/scope.yml
These commits affect only the comments (not the keys/values) in both `scope.yml` files:
1. Correct 'processes' spelling.
2. Change all 'whitelist' -> 'allowlist'.
3. Clarify 'commanddir' description.
=> scope.yml copy edits

website/src/data/documentationNav.yaml, website/src/pages/docs/changelog.md, website/src/pages/docs/config-files.md, website/src/pages/docs/examples-use-cases.md, website/src/pages/docs/installing.md, website/src/pages/docs/known-issues.md, website/src/pages/docs/library-using.md, website/src/pages/docs/loader-library.md, website/src/pages/docs/logstream-integration.md, website/src/pages/docs/quick-start-guide.md, website/src/pages/docs/what-do-with-scope.md
Includes basically:
- Added new doc section explaining scope connection to LogStream.
- Added v.0.6 Changelog entry [now assumes 4/1/21 as release date].
- Added Known Issues page [also assumes as of v.0.6, as of 4/1/21].
- Expanded instructions for displaying CLI help contents.
- Refactor the confused titling of (and kāpulu links to) the "Using the CLI" page (formerly "Quick Start Guide").
- Minor cleanup.
=> Docs 0.6 updates

src/wrap_go.c
Go tls is not interposed if we use metadata symbols. This is a temp workaround.
=> Go TLS with symbols in metadata

src/report.c
Support the partial write case in payload file output. 
Change payload names back to rip:rport_lip:lport so no change to the CLI is required.
=> Payload short writes

website/src/pages/docs/library-using.md
- CRIBL-4774 Add Lambda function steps to 'Using the Library' doc.
=> AppScope docs updates, post-0.6 release

website/src/data/documentationNav.yaml, website/src/pages/docs/changelog.md, website/src/pages/docs/other-resources.md
* Add a new docs page linking to existing AppScope blog posts and all Cribl videos.
=> Issue #260 Docs: Add blogs/videos page; add 0.6.1 changelog entry

src/wrap.c
fix #279
Built and tested on both Ubuntu 18.04 and 20.04.
=> Handle different gnutls_transport_get_ptr() results

.gitignore, Makefile, docker/builder/Dockerfile, docker/builder/Dockerfile.alpine, docker/builder/gdbinit
This adds a target to the top-level Makefile so we can `make docker-run` to fire up a working environment when we're on a host where this difficult (i.e. my Ubuntu 21.04 machine). Should work on MacOS too.
I've also tweaked the `docker/builder/Dockerfile` to use Ubuntu 18.04 instead of "latest" (which is 20.04 currently).
=> Add `make docker-run` target

cli/Makefile, cli/cmd/attach.go, cli/cmd/root.go, cli/cmd/run.go, cli/cmd/util.go, cli/cmd/watch.go, cli/flows/flow_file_test.go, cli/history/sessions_test.go, cli/run/run.go, cli/run/run_test.go
- make "attach" a command, not a flag, so that users can call "scope attach [PID]"
- make some of the help messages friendlier
- add a debug command to the makefile
=> attach command

website/src/components/criblSiteNav/index.js
Pretty straightforward here. Let me know if you have any questions. Essentially what happened is that 2 different wrapping components were creating anchor tags creating a conflict in terms of routing. Removed one of them and links are working again.
=> [MKTG-647] - Removed list item wrapper. 

src/inject.c
This is fix that allows injecting scope into a stopped process. Tested with the `top` command (in batch mode):
```
janusz@nuc:~/dev/appscope$ top -b & kill -s SIGSTOP $(pidof top)
[1] 977900
[1]+  Stopped                 top -b
janusz@nuc:~/dev/appscope$ sudo ./bin/linux/ldscopedyn --attach $(pidof top)
Attaching to process 977900
Appscope library injected at 0x561f4faa2f00
janusz@nuc:~/dev/appscope$ fg
top -b
top - 10:52:53 up 5 days,  2:13,  3 users,  load average: 0,29, 0,44, 0,62
Tasks: 328 total,   1 running, 327 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,8 us,  1,6 sy,  0,0 ni, 97,3 id,  0,0 wa,  0,0 hi,  0,3 si,  0,0 st
MiB Mem :  64036,8 total,  53957,5 free,   1513,1 used,   8566,2 buff/cache
MiB Swap:   2048,0 total,   2048,0 free,      0,0 used.  61664,3 avail Mem
....
```
=> fix #319 - Attach to background process is no bueno

cli/Makefile, test/testContainers/alpine/Dockerfile, test/testContainers/alpine/test_all.sh, test/testContainers/alpine/test_scope.sh
- add `CGO_ENABLED=0` to go build targets in the `cli/ Makefile`, to build scope as a static executable
- add an integration test in alpine to ensure that `scope` runs and exits without failure
- add an integration test in alpine to ensure that `scope` is a static executable
=> Build scope as a static executable #175

website/README.md
Replaced the stock Gatsby-generated README.md in the `website/` directory with notes for our docs guys.
=> Website README

cli/.golangci.yml, cli/Makefile, cli/bolton/bolton.go, cli/cmd/dash.go, cli/cmd/events.go, cli/cmd/flows.go, cli/cmd/history.go, cli/cmd/logs.go, cli/cmd/prune.go, cli/cmd/root.go, cli/events/events.go, cli/flows/flow.go, cli/flows/flow_test.go, cli/main.go, cli/metrics/metric.go, cli/util/newlinereader.go, cli/util/table.go, cli/util/table_test.go, cli/util/util.go
Changes in this PR fix a majority of lint issues generated by the `golangci-lint` linter.
Now that these changes have been made to historical work, I have added the argument `--new-from-rev=HEAD~1` to the linter, so that we will only be warned about new lint issues.
=> Resolve lint issues in the Cli

cli/cmd/prune.go
Currently there is a bug where the default for `scope prune -d` and `scope prune -k` is set to -1. This is not the intended user default. This fixes that.
- Change the default flag values to 0, so no default.
- Change the tests for keep and delete to look for >0 instead of >-1
=> Fix default value bug in scope prune

website/src/components/MarkDownBlock.js, website/src/pages/index.js
* Successor to [PR # 326](https://github.com/criblio/appscope/pull/326/).
* Cherry-picked @timothymwilson's 2 commits from "big" [PR # 326](https://github.com/criblio/appscope/pull/326/).
* Restored " | AppScope Docs" branding, at end of tab titles.
* Can we use this branch/PR to experiment with MKTG-654: Swap in AppScope-specific favicon, for docs/Gatsby subsite ONLY?
=> MKTG-614 Docs: Tabs ++page titles

cli/cmd/util.go, cli/run/attach.go, cli/run/run.go, src/cfgutils.c, src/com.c, src/scope_static.c, src/scopetypes.h
- Allow the user to set a flag `-n` or `--nobreaker` that will set an environment variable `SCOPE_CRIBL_NO_BREAKER` to `true` when starting scope with run or attach.
- Add `"breaker": "Cribl - Do Not Break Ruleset"` to the process start message when `SCOPE_CRIBL_NO_BREAKER` is true.
- Improve the way environment variables are read in ProcessEnvStyleInput by using `strcmp()` on the environment name in most cases, instead of "`startsWith()`.
Now, when the user sets `-n` in scope, the process start message looks as follows:
`{"format":"ndjson","breaker":"Cribl - Do Not Break Ruleset","info":{"process":...`
=> Add cribl no breaker option

package-lock.json, website/gatsby-browser.js, website/gatsby-config.js, website/package-lock.json, website/package.json, website/src/components/MarkDownBlock.js, website/src/scss/_documentation.scss
This PR does 3 things, each in 1+ separate commits:
1. Adds (industry-standard) visible & clickable links to the left of AppScope docs' headings.
2. Comments out all references to the PrismJS syntax highlighter. (We've never enabled this plug-in; it was lurking in the Gatsby codebase; and when we refactored the `gatsby-config.js` file's elements, to enable the links plug-in, that unleashed the Kraken and broke builds. We're not using it, so 'bye.)
3. Gives code blocks (`<pre>`) a 1980s green CRT foreground, matching the green color we've had all along on inline code (`<code>`).
This achieves the same result as its (closed) predecessor https://github.com/criblio/appscope/pull/375, but with a less-convoluted commit history. Here's that result, all elements visible on the **Using TLS** doc …
=> MKTG-648 Docs ++visible heading links, --PrismJS highlighting

cli/flows/flow.go, cli/flows/flow_test.go
- Fixes the bug listed in #310 by updating the regular expression.
- Tested with regular expression generator https://regexr.com/61eu8
- Validates these 3 filename formats generated by src/report.c: doPayload():
`44603_af_unix:198372_af_unix:198371.in`
`44603_127.0.0.53:53_0.0.0.0:0.in`
`44603_tlsrx:0_tlsrx:0.in`
Does not validate the `pid.na` format. This format will cause an error to be returned in `cli/flows/flow.go`. Should we expect to handle these pid.na files? @jrcheli
=> Scope flows bug #310

.dockerignore, .gitignore, Makefile, cli/util/proc_test.go, docker/builder/Dockerfile, docker/builder/Dockerfile.alpine
Closes #350
The idea here is to fix the permission issues Sean and I have been having when we use `make docker-build`. We end up with generated content owned by root which causes issues. 
* use `-u $(uid -u):$(id -g)` on the `docker run` command-line so the user in the container has the same UID/GID as us
* map those UID/GID values to a `builder` user in the container whos `$HOME` is `/home/builder`
* mount the local working copy of the repo at `/home/builder/appscope` in the container and make that the the `WORKDIR` too
I had to comment out one of the Go unit test cases that was assuming PID 1 belonged to "root" which is not the case when we build using this setup.
Added `.dockerignore` so some larger, unnecessary content is not included in the `docker build` context to speed things up. …
=> run `make docker-build` as non-root user

.github/workflows/website.yml
This should skip the website workflow when we commit to master without any changes in the `website/` content. Currently, we're redeploying the website when we commit anything to `master`.
=> Only deploy website on changed

src/wrap.c
While working on integration tests, I found the Alpine test was reliably stalling when run at GitHub but ran fine locally with `docker-compose run alpine`. Eventually discovered we could repeat the issue locally using `docker-compose up alpine` (`up` instead of `run`).
The call to `fileno()` was hanging due to it calling `FLOCK()` internally. Looking at other musl libc code, it looks like they're skipping `fileno()` and just using `f->fd` instead so we're now doing the same and the integration tests are passing.
=> fix hanging alpine tests

cli/run/scopeconfig.go, cli/run/scopeconfig_test.go, cli/run/setup_test.go, conf/scope.yml, src/scopetypes.h, test/evtformattest.c
Prior to this, we're mistakenly reporting access to things like `.../config/logger.yaml` as `log` events. See the updated test for expectations.
=> improve log file regex, update UT

docker/base/Dockerfile
Using the scope in our container with the TLS transport enabled isn't working because we don't have the CS certificates installed. This adds those certs.
=> Add Missing CA Certs to Container

cli/cmd/prune.go
- Provide an error message if a negative number is entered for `scope prune --keep X` or `scope prune --delete X`.
Closes https://github.com/criblio/appscope/issues/407
=> Prevent negative numbers in scope prune

cli/metrics/metric.go
- Added "Timer" to the metric types array, so that timer metrics can be displayed with the correct unit.
Closes https://github.com/criblio/appscope/issues/400
=> Add timer to metric types

cli/cmd/history.go, cli/history/sessions.go
- Set the `Duration` field in `scope history` to be `NA` whenever there is no event history (i.e. due to events being exported to cribl or another destination). The `Total Events` is already set to `NA` under this condition.
Closes https://github.com/criblio/appscope/issues/404
=> Improve scope history output when there is no event history

src/log.c, src/log.h, src/mtc.c, src/mtc.h, src/scopetypes.h, src/transport.c, src/wrap.c
npm uses git, which uses ssh. ssh has code that iterates through proc/pid/fds, and closes any file descriptors that don't belong to it. some of these file descriptors belong to us, and closing them results in a "bad file descriptor" error or a hang when we try to use them.
this PR fixes the complications that arise from the above, by effectively intercepting the close function to prevent scoped applications from closing file descriptors that our transport object is maintaining.
=> Resolve npm/git hangs due to bad file descriptor

src/scopetypes.h, src/transport.c, src/wrap.c
If a connection is required, we can now wait for it to be made for SCOPE_CONNECT_TIMEOUT_SECS before calling doEvent.
If we do not wait, and there is some connection latency, doEvent will not see a connection, and will not try to pull any data from the queue for sending.
Closes #395
=> Wait for connection before calling doEvent

src/transport.c
- fixes https://github.com/criblio/appscope/issues/418
Prior to this fix, when a server closed the connection prematurely, we were getting into a loop where SSL_read returned -1 continuously, and we were not able to break out of it.
=> TLS shutdown handling bugfix

cli/Makefile, os/linux/Makefile
Closes #449
Use `make build CMD="make all test COMPRESS=1"` to re-enable it at build time.
=> disable UPX compression of the CLI executable

test/testContainers/nginx/Dockerfile, test/testContainers/test_runner/ab.py
We found the default behavior of scope to reconnect to tcp:9109 for
events was impacting operation of Nginx. Not sure how - another ticket
coming for that. In the mean time, we've adjusted the env vars to
disable events and set the event destination to a file instead of a
socket.
We've also unset LD_PRELOAD when running `ab` since the intention of
this is to test scoped Nginx, not Apache Benchmark.
Closes #450
=> fix the nginx integration test

contrib/Makefile
Also added `no-tests no-unit-test` to the openssl build to save ~8secs
on x86 and ~2mins on ARM.
Closes #452
=> fix dependencies in contribs

cli/Makefile, cli/run/scopeconfig.go
Unconditionally add authtoken to scopeconfig, regardless of whether or not -c is set.
This supports mixing of the environment variable `SCOPE_CRIBL` and the `--authtoken` flag.
Closes #469
=> Add authtoken to config regardless of -c

cli/cmd/events.go, cli/cmd/metrics.go, cli/cmd/util.go
Prior to this, scope would attempt to create a graph when there are no metrics available, causing errors.
Closes #467
=> Exit scope metrics if metrics file is empty

src/report.c, src/report.h, src/wrap.c
Resolves #395 
Changed the sequence of events on exit. We weren't creating the connection until the periodic thread ran, which created more of a delay than was needed. We should report periodic detail instead of processing events during exit handling when the connection is established.
=> Updated the sequence of steps taken on exit.

src/dbg.h, src/gocontext.h, src/wrap_go.c
- add awareness to variadic functions about format specifier
Done while working on #514.
Changes from this patch will be included in another PR but the changes could be reviewed separately.
[Edit]
Example warnings, after adding compiler attribute: src/wrap_go.c:479:33: warning: format '%x' expects argument of type 'unsigned int', but argument 4 has type 'Elf64_Off {aka long unsigned int}' [-Wformat=]
are presented https://github.com/criblio/appscope/pull/523/checks?check_run_id=3492739359 (with run which only enabled the compiler attribute.
Current patch includes fixes for warnings.
=> Add PRINTF_FORMAT as compiler format attribute

src/state.c
- use calloc instead of malloc + memset
Found during work on other PR.
=> [Minor] Optimize initState() function 

os/linux/Makefile, src/ctl.c, src/state.c, src/state.h, src/state_private.h, test/ctltest.c, test/testContainers/README.md, test/testContainers/console/Dockerfile, test/testContainers/console/scope-test, test/testContainers/docker-compose.yml
Local test pass with a simple:
LD_PRELOAD=lib/linux/x86_64/libscope.so cat png file
and
/bin/linux/scope run -- cat png file
~Fail with curl command~
isprint - accepts besides digits, letters, space characters and punctuation characters which could be presented in the beginning of the e.g. HTML files
isspace - accepts characters like '\n' or '\r'
- Operation is done on ctlFlushLog on report side layer
- Verify beginning of the data to lookout for characters
different from printable or white-space
- Ref:
https://www.cplusplus.com/reference/cctype/isprint/
https://www.cplusplus.com/reference/cctype/isspace/
=> Detect binary data and avoid emits it

cli/cmd/completion.go, docker/base/Dockerfile
Completion of commands is enabled by calling:
source <(./bin/linux/x86_64/scope completion bash)
Fixes #361
Ref: https://github.com/spf13/cobra/blob/master/shell_completions.md#creating-your-own-completion-command
Tested with following binary: ./bin/linux/x86_64/scope
TODO:
=> Extend scope with "completion" command

os/linux/os.c, src/bashmem.c, src/cfgutils.c, src/com.c, src/ctl.c, src/dbg.c, src/dbg.h, src/javaagent.c, src/mtcformat.c, src/report.c, src/scopeelf.c, src/scopetypes.h, src/state.c, src/sysexec.c, src/transport.c, src/utils.c, src/wrap.c, src/wrap_go.c, test/testContainers/go/unsupported/Dockerfile, test/testContainers/go/unsupported/test_go.sh
Modify scopeLog logging mechanism : 
- modify handling scopeLog parameters  - use variadic function with format specifier as parameter to move message composition in scopeLog
- Enable logging mechanism inside constructor using SCOPE_ALLOW_CONSTRUCT_DBG=true
- ~~Buffer the logging before initialization of configuration~~
- Highly recommend to review this commit by commit
- Fixes: #514
=> Modify logging mechanism -  scopeLog

cli/Makefile
Fixes `make lint` stage in cli
=> minor: fix golangci-lint bin path in Makefile

cli/cmd/service.go, cli/run/scopeconfig.go, cli/run/scopeconfig_test.go
Scope config was uninitialized, so the program complained about a nil pointer dereference.
To fix this, I initialized it using the SetDefault() function. Please check the defaults set in that function to confirm these are the defaults you want.
Program no longer seg faults:
`The motd-news service has been updated to run with AppScope.`
Closes #464
=> Fix scope service bug

src/cfgutils.c, test/cfgutilstest.c, test/testContainers/go/net/plainClient.go, test/testContainers/go/net/tlsClient.go, test/testContainers/gogen/Dockerfile, test/testContainers/gogen/scope-test, test/testContainers/gogen/weblog.yml
Changed the hostname filter for custom configs to be case-insensitive
since that's how they are in DNS and elsewhere. We checked and username
are not case-insensitive so leaving that filter as is.
Closes #579
=> case-insentive hostname filter

.github/workflows/build.yml
The `is_semver` variable is set even though we've detected it's a branch
instead of one of our release tags; `v*`. We need to check for
`unreleased` in the `tag` variable instead. This should prevent the CI
workflow from creating the unwanted release and tag.
Closes #583
=> don't create release if tag is "unreleased"

.github/workflows/website.yml
We want the workflow to run when we push changes under website/ so it can update staging without the web* tag.
=> (499) run website workflow even without web tag

cli/Makefile, cli/cmd/dash.go, cli/cmd/flows.go, cli/cmd/util.go, cli/history/sessions.go, cli/run/run.go, cli/run/run_test.go, cli/run/scopeconfig.go, cli/run/setup.go, cli/util/proc_test.go
This PR provides the user with the option to configure scope with a file, like so:
`scope run -u ~/scope.yml -- top`
`scope run --userconfig ~/scope.yml -- top`
Scope will create a session directory for the session, and the config file will be copied to that directory.
**Design Decision 1**
This config file is parsed at some point, in order to validate _some of_ the contents ; and to create metric and event files in the right places (explained later), but the config file is copied to the session directory directly using file io from the user specified file. By design, there is no intervention by scope. The config you pass scope is the config that will be loaded by ldscope.
**Design Decision 2**
All runtime options that modify the config will be ignored, essentially overridden by the …
=> Add a user config option to scope

test/testContainers/java/test-ssl.sh
- prevent infinite waiting loop in case of issue
with starting Tomcat
- closes: #635
=> Java test - add max retry for curl waiting loop

test/testContainers/alpine/test_tls.sh
Avoid create certs dir in Appscope working dir
Calling scipt:
`/opt/test/bin/testssl.py create_certs`
Results with the creation of `certs` dir - owned by Docker
container user - `root`. Later trying to remove `certs` dir
as a user different than `root` results with permission denied.
Alpine integration test working directory is always
`/opt/appscope` this results in the creation of the `certs` dir
outside of the container and the `certs` dir will be available
after the test.
Removing the `certs` directly from the host (outside the Docker
container) results with permission denied and issues with
cleaning up the test environment for future test runs.
Changing the test working directory to `/opt/test` solve the
initial problem.
=> Avoid creating certs dir in Appscope working dir

cli/cmd/excrete.go, cli/run/excrete.go, src/scope_static.c, test/testContainers/README.md, test/testContainers/docker-compose.x86_64.yml, test/testContainers/docker-compose.yml, test/testContainers/glibc/Dockerfile, test/testContainers/glibc/scope-test, test/testContainers/musl/Dockerfile, test/testContainers/musl/scope-test
The intention of this PR is to provide support for ldscope on ARM:
TODO:
~~- [ ] Extend building library with the stage where we reserved a place for the loader in the previously mentioned sections~~
~~- [ ] Add test where loader path size is extending the original loader path size~~
~~- [ ] Check the syscalls integration test on musl (x86_64 and aarch64)~~ - will be done in another PR
=> Enable basic ldscope on aarch64/libmusl

.github/workflows/build.yml
- enable to run GitHub workflow with integration tests, when
changing Pull Request state from "Draft" to "Ready to review"
- "By default, a workflow only runs when a pull_request's activity type
is opened, synchronize, or reopened. To trigger workflows for more
activity types, use the types keyword."[1]
Link: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request [1]
=> Extend triggering workflow config for PR event

src/dbg.c, src/wrap.c
Add timestamp to scope logs in RFC 3339 format.
Closes https://github.com/criblio/appscope/issues/534
**QA INSTRUCTIONS**
**Part 1**
Do:
```
$ SCOPE_LOG_LEVEL=debug scope top
```
Ctrl+c
```
$ scope logs
```
Expect:
You see timestamps in the logs:
```
Scope: top(pid:83214): [2021-10-20 17:48:33.972] fd:5 lseek
Scope: top(pid:83214): [2021-10-20 17:48:33.972] fd:7 lseek
Scope: top(pid:83214): [2021-10-20 17:48:33.972] fd:4 rewind
Scope: top(pid:83214): [2021-10-20 17:48:36.974] fd:6 lseek
Scope: top(pid:83214): [2021-10-20 17:48:36.974] fd:5 lseek
```
=> Add timestamp to scope logs

cli/util/util.go
- simplifies selecting Event ID as used characters
considered part of a word
Closes #549
=> Limit codes to numeric and alphabet characters in Event ID

src/state.c, test/testContainers/console/scope-test
- avoid stack overflow with `doWrite` when log destination path
is file
`doWrite`
|
'scopeLog'
|
'logSend'
|
'transportSend'
|
'__write_libc'
|
`doWrite`
...
closes #645
=> Remove scopeLog call which results with stack overflow

src/scope_static.c, src/wrap.c, test/testContainers/README.md, test/testContainers/docker-compose.x86_64.yml, test/testContainers/docker-compose.yml, test/testContainers/elastic/scope-test, test/testContainers/glibc/scope-test, test/testContainers/syscalls/Dockerfile, test/testContainers/syscalls/Dockerfile.alpine, test/testContainers/syscalls/scope-test, test/testContainers/syscalls/syscall_tests_conf.json, test/testContainers/test_runner/app.py, test/testContainers/test_runner/runner.py, test/testContainers/test_runner/scope.py, test/testContainers/test_runner/syscalls.py, test/testContainers/test_runner/watcher.py
The root cause of failing test:
- the `msghdr` structure implementation in musl is compatible with POSIX standard [1]
- the `msghdr` structure implementation in glibc is not compatible with POSIX [2][3]:
```
"According to POSIX.1, the msg_controllen field of the msghdr
structure should be typed as socklen_t, and the msg_iovlen field
should be typed as int, but glibc currently types both as size_t."
```
- `msghdr` structure according to POSIX standard includes at least the following members [4]:
```
void         *msg_name;
socklen_t     msg_namelen;
struct iovec *msg_iov;
int           msg_iovlen;
void         *msg_control;
socklen_t     msg_controllen;
int           msg_flags;
```
- `msghdr` structure implementation on glibc:
```
struct msghdr {
void         *msg_name;
socklen_t …
```
=> Extend syscall tests to musl 

src/ctl.c, test/testContainers/console/Dockerfile, test/testContainers/console/scope-test
- extend tests with one which confirms fix: `ls --color=always`
- extend tests with negative tests (`xxd`, `hexdump`)
- closes: #574
=> Exclude ASCII escape character from binary data detection

cli/run/run_test.go, src/com.c, test/comtest.c, website/src/pages/docs/cli-using.md
Ref #229 
~~- [ ] not strictly related to the original issue but more with converting the `uid` and `gid` values to names e.g. in Agent (@pdugas). Looking up for these values can be non-portable so the idea is to retrieve it and store it on the Appscope side
Ref: https://man7.org/linux/man-pages/man3/getpwent.3.html~~
=> Collect uid and gid

src/transport.c, src/transport.h, src/wrap.c
While waiting for actual connection (when TCP connection is
pending) the socket was already created by the AppScope and
stored in `net.pending_connect` field.
The file descriptor returned by the `socket` function will be
the lowest-number file descriptor not currently open for the
process[1] e.g. with value equals 3.
The scoped application can try to use low id file descriptor for
`dup2(oldf,newfd)` function. If the new file descriptor (`newfd`)
will be equal to file descriptor previously used for socket
creation, then the socket will be silenty closed [2] and file
descriptor will be reused for the application purpose:
duplication of `oldfd`.
After this operation value stored in `net.pending_connect` does
not point longer to a socket initially created by the AppScope.
The file descriptor …
=> Fix overwrite file descriptor owned by the AppScope by the application (dup2)

src/wrap.c
Change it from previous format [1]:
e.g. "2021-10-20 17:48:33.972"
To ISO 8601:
YYYY-MM-DDThh:mm:ss.sTZD
e.g. "1997-07-16T19:20:30.45+01:00"
Link: #618 [1]
closes #678
=> Modify timestamps format (add time zone info)

website/deploy.sh
The last time a website build was successful was Nov 2nd:
https://github.com/criblio/appscope/actions/runs/1418204929
We believe that it was due to a change of default versions of npm and node provided by our github builders...
https://github.com/actions/virtual-environments
=> Update website/deploy.sh to account for updated node version.

test/testContainers/glibc/scope-test
- valid against following format YYYY-MM-DDThh:mm:ss.sTZD
(e.g.: "1997-07-16T19:20:30.452+01:00")
- ref: 53129d7
- Ref: #678
=> Add test for timestamp format

test/testContainers/console/Dockerfile, test/testContainers/console/scope-test
closes #624
The following test pass on the current master branch but it fails on e.g. `v0.8.0-rc0` tag (state before PR #621)
=> Add firefox test

os/linux/os.c, os/linux/os.h, src/scope.c, src/wrap.c, test/options.sh
Resolves #640 
We don't support attach to a process started from a static executable. Add checks for static and emit a descriptive message.
=> Check for attach to a process started from a static exec

src/cfgutils.c, test/integration/cli/test_edge.sh
- fix missing support for `edge` when using `scope run --cribldest`[1]
- the similar solution was already presented for the UNIX destination path
[2]
Link: 227e82c [1]
Link: 5e395d3 [2]
This Pull Request is an additional fix (post fix) for functionality introduced for the issue: #670 in Pull Request #688
Related: https://github.com/criblio/appscope/issues/700
- AppScope cli 
- `edge` transport type as `cribl` destination
Terminal 1 - start server listening on UNIX socket /opt/cribl/state/appscope.sock
```
docker run --rm -it cribl/scope:<VERSION_ID>
apt update && apt install netcat -y
mkdir -p /opt/cribl/state/
nc -lU /opt/cribl/state/appscope.sock
```
Terminal 2 - start scoping `ls` using `cribldest`
```
docker exec -it <AppScope_container> bash
scope run -c edge ls
```
Observe that you …
=> Add `edge` support for cfgLogStreamDefault

src/report.c, src/report.h, src/wrap.c, test/integration/http/Dockerfile, test/integration/http/scope-test
This PR re-instates http aggregation as it was intended. In recent changes, we inadvertently aggregated and sent http metrics every 1ms. We are moving the calls to aggregate http metrics from `doEvent()` into the periodic thread, in the block that runs every [summary time (default 10s)]. As a result, we should see http metrics with the same target and status code be aggregated over periods of 10 seconds.
This PR also adds integration tests to ensure that: aggregation is happening ; http metrics are still sent when we exit before the summary period ends (i.e. 5 seconds).
See #232 for issue and QA instructions.
=> Fix http aggregation 

src/cfgutils.c
This is a temporary thing to make today's lunch and learn demo go more smoothly.
I'm leaving #707 to do this in a more robust way.  I suspect that we'll need to do more than is being done here to make sure that appscope will be able to connect to edge even if this socket isn't created before appscope is started.
=> Added /var/run/appscope/appscope.sock as the first option for edge.

src/fn.c, src/fn.h, src/report.c, src/report.h, src/state.c, src/state.h, src/wrap.c, test/integration/syscalls/syscall_tests_conf.json
This PR adds interposing of the `unlink` and `unlinkat` system calls, wrapping the calls and generating `fs.delete` events to notify the user of file removal.
**Considerations**
- We created a new metric type `FS_DELETE`, since there was no appropriate `DELETE` type in existence. We now handle that type in doUpdateState() and on the reporting side in doFSMetric().
- We decided that there was no need for error handling in the unlink function i.e. we don't need to report an error with unlinking. 
**Testing**
- Integration tests for unlink, unlinkat were added to the syscalls tests. This can be tested with the following commands:
```
cd test/integration
make syscalls # runs in a container
```
- QA instructions can be found [here](https://github.com/criblio/appscope/issues/709)
**Questions …
=> Add support for fs delete (unlink/unlinkat) events

src/state.c
While testing http performance in #614 we noticed two bugs in `doDupSock()`.
- When duplicating the socket, we weren't creating a new unique ID for the net object.
- When duplicating the socket, the call to `memmove()` had an incorrect length argument causing adjacent memory to be overwritten. The result of this in our testing was that there appeared to be an active, valid net object stored in g_netinfo[4] which was not the case. When `doSend()` was called and nginx tried to write to the `access.log` file on file descriptor 4, it was incorrectly perceived as a net object.
We recently added a call to `doDupSock()` in `doAccept()` which is why we noticed these today.
This PR fixes both of these bugs.
=> Fix bugs in doDupSock()

src/ctl.c, test/ctltest.c
We want to ensure that a channel field is always provided, even when unknown, for schema consistency.
Currently, `fs.delete` events do not include a channel field. This is because `unlink` operations do not provide a file descriptor, so we do not add an fs object to our array of known files. Therefore, when we call `postFSState()` we pass a null fs object (uid = 0). When the `fs.delete` event is emitted, the channel field is not included since uid is 0. This PR sets the channel field = "none" where uid is 0.
Now the fs.delete event looks as follows:
`{"type":"evt","id":"vm-rm-rm deleteme","_channel":"none","body":{"sourcetype":"fs","_time":1643825519.802053,"source":"fs.delete","host":"vm","proc":"rm","cmd":"rm deleteme","pid":84066,"data":{"proc":"rm","pid":84066,"host":"vm","op":"unlinka …
=> Add channel field to fs.delete events

src/ctl.c, src/metriccapture.c, src/scopetypes.h
**Before this PR**
The default buffer size for _events, logs and metric capture_ is:
`DEFAULT_CBUF_SIZE`
which is calculated from:
```
DEFAULT_MAXEVENTSPERSEC (10,000)
*
DEFAULT_SUMMARY_PERIOD (10) [seconds]
=
100,000
```
This calculation ensures that the ring buffer size complies with the max events limit.
The default buffer size for _payloads_ is:
`DEFAULT_PAYLOAD_RING_SIZE`
which is:
`10000`
**After this PR**
This PR joins `DEFAULT_PAYLOAD_RING_SIZE` and `DEFAULT_CBUF_SIZE` into `DEFAULT_CBUF_SIZE` ; and it adds the possibility to set an environment variable `SCOPE_QUEUE_LENGTH`.
The behavior when creating a buffer has been updated as follows:
Default payload buffer size, event buffer size, log buffer size, metric capture buffer size =
```
DEFAULT_MAXEVENTSPERSEC (10,000)
* …
```
=> Configure the queue size

cli/cmd/flows.go
This PR
- Improves the description and provides an example in the help menu for `scope flows --peer`.
- Adds more field types to the `scope flows --sort` option (string, duration, int64), to reduce errors.
- Improves the description for the `scope flows --reverse` option. (Must be combined with --sort).
Closes #763
=> Improve scope flows

cli/cmd/util.go
- Fixed the newline error reported in #509. Now the prompt works as expected:
```
sean@vm:~/src/appscope-dev/cli$ rm ~/.scope/history/curl_*/event_dest
sean@vm:~/src/appscope-dev/cli$ rm ~/.scope/history/curl_*/events.json
sean@vm:~/src/appscope-dev/cli$ ../bin/linux/x86_64/scope events
Invalid session, likely an invalid command was scoped or a session file was modified. Would you like to delete this session? (y/yes)
n
No action taken
```
```
sean@vm:~/src/appscope-dev/cli$ ../bin/linux/x86_64/scope events
Invalid session, likely an invalid command was scoped or a session file was modified. Would you like to delete this session? (y/yes)
No action taken
```
```
sean@vm:~/src/appscope-dev/cli$ ../bin/linux/x86_64/scope events
Invalid session, likely an invalid command was scoped or a …
```
=> Fix newline bug in user prompt, and improve 0 sessions error message

cli/cmd/metrics.go, cli/util/table.go
- Add example to the `scope metrics` help menu to show how to use multiple metric names (commit 1)
- Improve the descriptions in the `scope metrics` help menu (commit 1)
- Fix a bug where scope would exit before printing some metrics (commit 1):
Occasionally, `scope metrics` would not display all metrics.
When the cli writes output to the metrics table, it sends output to a goroutine that takes care of tab replacement (for proper alignment) and truncation (for proper table width) before forwarding it to stdout.
Scope was exiting after sending the metrics to that goroutine, killing it sometimes before the data got out to the terminal. This PR tells the main thread to wait until that goroutine is finished processing before exiting.
- Fix a bug where columns would not display correctly when …
=> Fix scope metrics issues in cli

docs/schemas/event_dns_req.schema.json, docs/schemas/event_dns_resp.schema.json, docs/schemas/event_fs_close.schema.json, docs/schemas/event_fs_delete.schema.json, docs/schemas/event_fs_duration.schema.json, docs/schemas/event_fs_error.schema.json, docs/schemas/event_fs_open.schema.json, docs/schemas/event_fs_read.schema.json, docs/schemas/event_fs_seek.schema.json, docs/schemas/event_fs_stat.schema.json, docs/schemas/event_fs_write.schema.json, docs/schemas/event_http_req.schema.json, docs/schemas/event_http_resp.schema.json, docs/schemas/event_net_app.schema.json, docs/schemas/event_net_close.schema.json, docs/schemas/event_net_duration.schema.json, docs/schemas/event_net_error.schema.json, docs/schemas/event_net_open.schema.json, docs/schemas/event_net_other.schema.json, docs/schemas/event_net_port.schema.json, docs/schemas/event_net_rx.schema.json, docs/schemas/event_net_tcp.schema.json, docs/schemas/event_net_tx.schema.json, docs/schemas/event_net_udp.schema.json, docs/schemas/event_notice.schema.json, docs/schemas/event_stderr.schema.json, docs/schemas/event_stdout.schema.json
-  when `SCOPE_TAG` is defined it will be included in `body`
=> Remove `additionalProperties` condition for `body`

src/wrap.c
Don't let the reporting thread start while in the constructor.
=> tail crashes when our signal is delivered

cli/cmd/dash.go, cli/cmd/flows.go
When payload files are missing (most often due to the user not enabling payloads with -p), the existing error message is confusing. That is improved in this PR.
When viewing the help menu in the cli, the description for `scope dash` does not inform the user of the capability to work with previous sessions as well as live sessions. That is improved in this PR.
=> Improve cli error messages

test/integration/elastic/Dockerfile, test/integration/test_runner/elastic.py, test/integration/test_runner/requirements.txt
Update elasticsearch image to version 8.0.0
- in 8.0.0 default user is elasticsearch not root
- disable Elasticsearch security [features](https://www.elastic.co/guide/en/elasticsearch/reference/current/release-highlights.html#_better_protection_for_system_indices) as used in version 7.8.1
- for elasticsearch 8.0.0 the base docker image is Ubuntu 20.04.3 LTS previously was CentOS Linux 7 (Core)
=> Update elasticsearch integration test to 8.0.0 

.github/workflows/build.yml, website/README.md
This PR modifies the github actions configuration to prevent running unnecessary jobs, which should reduce the time we spend waiting for integration tests to run:
- Jobs that are superceded by newer commits will be cancelled mid-workfow
We should test this on this branch:
- Push dummy changes, then push to undo them, and monitor git actions to validate cancelled prior workflow
=> Set concurrency limit in github actions

cli/Makefile
"Starting in Go 1.17, installing executables with `go get` is deprecated.... In Go 1.18, go get will no longer build packages"
- Ref: https://go.dev/doc/go-get-install-deprecation
Closes #866
=> Convert `go get` statements to `go install`

src/sysexec.c
when scoping an executable argv[0]=`ldscopedyn` and argv[1]=`procname`
when we scope a static executable we call exec() with argv[optind], so in unmap_all, if we're in the context of a static executable, we need to reference argv[0] not argv[1] to get procname.
**Testing**
QA Instructions: #862 
Closes: #862
=> Fix bug in unmap_all that occurs when scoping a go static executable

docs/schemas/definitions/data.schema.json, src/gocontext.S, src/gocontext.h, src/wrap_go.c, test/integration/go/Dockerfile, test/integration/go/net/plainClient.go, test/integration/go/syscalls/readdir.go, test/integration/go/syscalls/unlinkat.go, test/integration/go/test_go.sh
The initial task was to provide interpositions for these system calls in go, to achieve parity with interpositions in libc:
- `unlink`
- `unlinkat`
- `opendir`
- `closedir`
- `readdir`
After inspecting go source code and verifying with disassembled output (`objdump -D some-go-app`) I noticed that:
1. go syscall unlink is a wrapper around unlinkat; and when os.Remove is called in go code, syscall unlinkat is used. So we do not need to interpose unlink, only unlinkat.
2. go syscall open is a wrapper around openat; and when os.Readdir is called in go code, syscall openat is used. We already interpose openat.
3. There is no syscall for closedir in the go code; when close is called on a directory in go code, syscall close is used. We already interpose close.
4. There is no syscall for readdir …
=> Interpose go unlink (unlinkat) and readdir (getdents)

test/integration/go/net/plainClient.go, test/integration/go/net/tlsClient.go, test/integration/go/test_go.sh
Current integration tests for go only check for a subset of expected events.
This PR updates those tests to check for all expected events.
This will provide the additional coverage required to validate go 1.17+ work.
**Discovered Failures**
go 16 dynamic/static: missing `net.close` in the "plainClient" and "tlsClient" integration tests (intermittent).
Resolution: The close is not always generated in the timeframe of our test app. So do not expect a close of the http connection in the "plainClient" integration test.
=> Update integration tests for go <=1.16

docker/docs/Dockerfile
- address the severity issues
- ref: https://snyk.io/advisor/docker/node
- Output md file is the same for `node` and `node:17.9-slim` 
- To test it call make docs-generate and examine the `./docs/md_files/schema-reference.md`
=> Update base docs docker image

test/integration/splunk/Dockerfile
In pip install version 22.0 - Python 3.6 support was dropped [1]
Use alternative link including Python version for install pip
Avoid following error:
ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
Ref: [1]https://github.com/pypa/pip/pull/10641
=> Splunk test Fix bootstrap Python 3.6 build error

src/wrap_go.c
Closes: #908 
Current state - Getting a seg fault. As seen in GDB when scoping `tlsClient18`:
```
Thread 2.6 "tlsClient18" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcdcb5640 (LWP 1343130)]
0x00007ffff76ef86e in scopelibc_memcpy () from /tmp/libscope-1.0.3/libscope.so
```
Backtrace
```
(gdb) bt
#0  0x00007ffff76ef86e in scopelibc_memcpy () from /tmp/libscope-1.0.3/libscope.so
#1  0x00007ffff76d8756 in scope_memmove (dest=0x7ffff64c4690, src=0xc00038e060, n=524288) at src/scopestdlib.c:254
#2  0x00007ffff76dd696 in c_str (go_str=0xc00014f288) at src/wrap_go.c:237
#3  0x00007ffff76df206 in c_open (stackaddr=0xc00014f278 "\001\001") at src/wrap_go.c:952
#4  0x00007ffff76dee67 in do_cfunc (stackptr=0xc00014f278 "\001\001", cfunc=0x7ffff76df1c3 <c_open>, …
```
=> Fix pathname in go 16 events

website/src/pages/docs/changelog.md
thanks, @seanvaleo , for pointing out the stray dot that made a link bad in the 1.0.0 Changelog.
=> remove stray dot in URL

website/src/data/corpSiteNav.yaml, website/src/data/documentationNav.yaml, website/src/data/header.yaml, website/src/data/readyGetStarted.yaml, website/src/pages/docs/community.md
1.
The `corpSiteNav.yaml` was still talking about LogStream etc, fixed that.
2.
The `documentationNav.yaml` had a cateogory of **COMMUNITY** for a single page called **Community**. Changed the category to **PARTICIPATE** ... not 100% happy with that, if someone has a better suggestion.
3.
a.
The `header.yaml` had an "Overview" link which was not needed per PM (and also confusing because it didn't link to the Overview page). Deleted that.
b.
The same header's Community link now links to the AppScope Community page in the docs, per PM.
4.
The `readyGetStarted.yaml` link to Community now links to the sign-up for Cribl Slack.
5.
The "Community" page in docs also now has a Join our Slack link that links to the sign-up and mentions the `#appscope` channel.
=> change menus and links per PM

website/src/pages/docs/cli-reference.md, website/src/pages/docs/cribl-integration.md
- `libary` -> `library`
- `specificied` -> `specified`
=> Fix typos in `website`

contrib/musl/arch/aarch64/syscall_arch.h, contrib/musl/arch/x86_64/syscall_arch.h, contrib/musl/src/internal/syscall.h, contrib/musl/src/internal/vdso.c, contrib/musl/src/sched/sched_getcpu.c, contrib/musl/src/time/clock_gettime.c, os/linux/Makefile, os/linux/os.c, src/scopestdlib.c, src/scopestdlib.h, src/state.c, src/wrap.c, test/execute.sh, test/vdsotest.c
This Pull Request contains two changes:
- Replace __xstat with stat:  remove `_STAT_VER` usage closes #307
- Improve the performance of time related functions - see details [here](https://github.com/criblio/appscope/pull/860#issuecomment-1106524685)
Below are comparison results 
```
#define IT_MAX (1000000)
struct timeval tv;
size_t i = 0;
for (; i<IT_MAX; i++) {
//scope_init_vdso_ehdr();
scope_gettimeofday(&tv,NULL);
}
```
```
Time elapsed: 0.151822 s (using syscall variant)
Time elapsed: 0.024110 s (using VDSO variant)
```
=> Internal libc - use VDSO function variants & remove `_STAT_VER` usage

os/linux/Makefile, src/wrap_go.c
- use function pointer solution and avoid checking for go version each time
@iapaddler @jrcheli
I have provided a form of safety mechanism for indexes & layout dependency with `go_16_schema` and `go_17_schema`.
The indexes for the `.tap` array are defined in single place in form of `enum` used both by `go_16_schema` and `go_17_schema` with a following [mechanism](https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html).
The exact value in the enum doesn't matter since you can give the elements in any order with designated inits.
Just FYI: If we extend the  `go_16_schema` or `go_17_schema` and by mistake we copy&paste the same index which was already used this situation will be detected during compilation and treated as an error - see the commit: 1fd22d2
=> Optimize calling go hook variants functions

test/integration/http/Dockerfile, test/integration/logstream/Dockerfile, test/integration/transport/Dockerfile
Not sure if this can be related to stability/flakiness with the http test as mentioned [here](https://github.com/criblio/appscope/issues/865) but it is still to worth test latest version instead of RC.
- add `DEBIAN_FRONTEND=noninteractive` to avoid
configuring `tzdata`
- comment regarding version below doesn't apply anymore
- ref: 6856c69
=> [Integration test] Update http-test to use latest cribl version

src/wrap_go.c
- remove unnecessary reference to `pthread.h`
- remove macro for indexed `.assembly_fn` definitions to make code more readable
- remove commented out `runtime.exit.abi0` hook. We now resolve the native symbol `runtime.exit`, and understand why.
- change the lookup for `.gopclntab` to a find a submatch instead of an exact match (in pie executables, the name of the .pclntab section is prefixed).
- remove the search for an alternate symbol in go12-17 symbol lookup.
- update a comment that referenced the legacy go_switch function/s.
- don't add a base offset to our internal symbol address of go version in stripped pie executables.
=> Go code improvements

website/README.md
- the local development server runs on
`http://localhost:8000` not `https://localhost:8000`:
npm run develop
results with following message
```
You can now view appscope in the browser.
⠀
http://localhost:8000/
```
ref: https://www.gatsbyjs.com/docs/quick-start/
=> [Readme] Fix local development website link reference

test/integration/docker-compose.x86_64.yml, test/integration/docker-compose.yml
- bash memory fix requirement was removed with aa710bb
Closes #427
=> Enable bash test for `aarch64`

test/integration/alpine/Dockerfile, test/integration/syscalls/Dockerfile, test/integration/syscalls/Dockerfile.alpine
- Alpine latest points to `3.16.0` [1]
- default Python version is 3.10 there [2]
Link: https://github.com/docker-library/official-images/commit/6675d08 [1]
Link: https://github.com/docker-library/python/commit/1a63123 [2]
The other commit is just a cosmetic change to store used version of LTP in single variable via Docker ARG
=> Fix failing alpine based integration tests - dependency issue with python

src/cfgutils.c, test/cfgutilstest.c
=> output the cribl section when outputting config

cli/libscope/config.go, cli/run/scopeconfig.go, cli/run/setup_test.go, test/integration/cli/expected.yml
We wanted to set `allowbinary` to false by default when the cli is used so that the cli can be used to display events without binary data appearing.
First we tried to explicitly set the `allowbinary` field to false, but by doing so this meant it was omitted in scope.yml output.
We then tried to disable the `omitempty` setting for that field, but that meant that the `allowbinary` field was included and set to false for _all_ event watchtypes. This was not a good solution since the `allowbinary` setting only applies to console events at this time.
I changed the `allowbinary` field to a string. Strings are included in the yml file directly without quotations... usually. It turns out that only for string values “on/off/true/false”, the quote marks remain in the yml output. The marshaller …
=> Set console events to `allowbinary=false` in cli defaults

website/src/pages/docs/config-file.md
@iapaddler @jrcheli @seanvaleo @michalbiesek
In #1011, John just noted that once this markdown version of the config file is done, we need to reconcile it with the *real* config file. Just FYI, everybody.
Question: There are 7 mentions of Cribl Stream, and none of Cribl Edge. Can we go through and see where (if anywhere) Cribl Edge should be mentioned too?
Minor point: This file seems to use backticks as if it were markdown, but since it's a big text block within a markdown page, the backticks don't have the desired effect. Or maybe that's a convention in config file comments that I'm not familiar with. Not sure there's anything to do about this, but I'm curious.
=> Docs/947 Config file wording tweaks

docker/docs/schema2md.js, website/src/components/layouts/documentationLayout.js
This PR contains two tiny unrelated fixes.
- One adds an OpenGraph meta image tag so that if somebody posts a link to our docs on Twitter or LinkedIn, the correct image will appear in the tweet/post. 
- The other improves readability the schema reference by breaking long lists into columns.
Thanks to @jakub-cribl for these fixes!
=> Docs/commits from Jakub

test/integration/syscalls/Dockerfile.alpine
It looks like legacy version of `pip3` poorly manage situation when
distutils is already present in OS.
`pip3` in `Alpine 3.15` is 20.3.4
`pip3` in `Alpine 3.16.1` is 22.1.1
Ref: https://github.com/pypa/pip/commit/b728bdad2a4fe29f2eedb8f37bdeefc1f60e756d
=> Fix `pip3 install virtualenv`

cli/run/attach.go
- provide exit status message without panic
Closes #1067
```
docker run --privileged --rm -it cribl/scope:dev-x86_64
top &
top &
scope attach top
Found multiple processes matching that name...
ID	PID	USER	SCOPED	COMMAND
1 	16 	root	false 	top
2 	17 	root	false 	top
Select an ID from the list:
```
When choosing `3`, you should see:
```
Invalid Selection
```
Instead of panic described in #1067
=> (#1067) Fix attach process by name error: index out of range

.github/workflows/update_latest.yml, docs/RELEASE.md
Resolves #1003 
This is a follow-on of sorts to https://github.com/criblio/appscope/pull/1077.  We merged 1077, then made a set of commits directly to master until it ran successfully in d517617c66bb7a07054abb53004e52268b9cca31.
As you can see here: https://github.com/criblio/appscope/actions/runs/2848753162
d517617c66bb7a07054abb53004e52268b9cca31 ran successfully, with the manual input of "1.1.2".  By "successfully", I mean that both the cdn and dockerhub have the desired latest tag of 1.1.2 after this manual run of the update_latest github workflow.
So, the goal of this PR is to remove the need to manually input the tag as a text string, and make sure that the tag passes some basic validation before we update the cdn and dockerhub.
When this is merged, I'm hoping that we can run the …
=> Add input version validation to .github/workflows/update_latest.yml 

src/scope.c, src/sysexec.c
=> Work around a segfault caused by x86_64 emulation on arm64.

src/ns.c, src/scope_static.c
Test instructions:
```
docker run --name redis_test -d redis:latest
```
```
pgrep redis
copy scope.yml scope_modified.yml
```
From:
```
cribl:
#
enable: true
```
To:
```
cribl:
#
enable: false
```
```
sudo SCOPE_CONF_PATH=<path_to_scope_modified.yml> ./ldscope -a <redis_pid>
````
```
docker exec -it redis_test bash
apt update -y && apt install netcat -y
nc -l -p 9109
```
You should see data on the screen
=> (#1061) Use `SCOPE_CONF_PATH` during attach from host to container

src/wrap.c
=> Don't emit console events in a musl libc distro when detached. 

cli/cmd/attach.go, cli/cmd/detach.go, cli/cmd/ps.go, cli/loader/loader.go, cli/run/attach.go, src/scope.c, src/setup.c, src/setup.h, src/wrap.c, test/integration/cli/test_cli.sh, website/src/pages/docs/cli-reference.md
Ref #1107 
~~- [ ] Handle the scenario when we attach to an already scoped process should we overwrite the scope configuration always?~~
We overwrite the configuration during reattach
=> Add detach in scope cli

src/scope.c
- unlink dynamic configuration file before creating a new one
Closes #1123
=> (#1123) Fix file sealing on tmpfs

src/ns.c, src/scopetypes.h, src/wrap.c
Add support for file interpretation in  SCOPE_FILTER
- SCOPE_FILTER=false - disables the handling the filter file
- SCOPE_FILTER=/tmp/myfile - will cause that `/tmp/myfile` will be interpreted as a filter file
Testing:
create `/tmp/myfile`
```
deny:
- arg: htop
```
1. Run ldscope without filter file in `/tmp/scope_filter` or `/usr/lib/appscope/scope_filter`
```
./bin/ldscope htop
ls -la /proc/<htop_pid>/fd
```
Observe that there is no "deleted" file there. The application is scoped.
1. Run ldscope with custom path filter
```
SCOPE_FILTER=/tmp/myfile ./bin/ldscope htop
ls -la /proc/<htop_pid>/fd
```
Observe that there is  "deleted" file there. The application is not scoped. Our library is loaded but we are in the state that the application was never scoped during it's lifetime
=> SCOPE_FILTER extend support

cli/start/start.go
`os.Stdin` for the following scenarios works in the modes:
scope start -f <empty> -  `fs.ModeCharDevice`, Unix character device cat <file> | scope start -f  -  `fs.ModeNamedPipe`, named pipe (FIFO) Edge -  `fs.ModeSocket`, Unix domain socket`
scope start -f < <file> -  No mode is defined
=> Fix `os.Stdin` handling for Edge

conf/example_filter.yml
- Watchtype formatting is correct allowing events to be emitted
- File now reads in the same order as our yml config
- TCP ports now match edge input source by default
=> Fix bug in event watchtypes in example_filter.yml

test/manual/clonetest.c, test/manual/namespace/ns_setnstest.c, test/manual/namespace/ns_unsharetest.c
- add `setns` and `unshare` tests to verify library behavior after switching namespace
- add clone test
=> [Manual Tests] extending

conf/example_filter.yml, conf/scope.yml, website/src/pages/docs/config-file.md, website/src/pages/docs/filter-file.md
The intention is to fix the formatting `scope_minimal.yml` file.
We use the following snippet to generate a stripped-down version of the `scope.yml` config.
```
egrep -v '^ *#.*$' scope.yml | sed '/^$/d' >scope-minimal.yml
```
With the presence of trailing whitespaces, we generate a file as follows (see e.g. `watch` section in):
```
metric:
enable: true
format:
type: statsd
statsdprefix:
statsdmaxlen: 512
verbosity : 4
watch:
- type: statsd
- type: fs
- type: net
- type: http
- type: dns
- type: process
transport:
type: udp
host: 127.0.0.1
port: 8125
tls:
enable: false
validateserver: true
cacertpath: ''
event:
enable: true
format:
type: ndjson
maxeventpersec: 10000
enhancefs: true
watch:
- type: file
name: (\/logs?\/)|(\.log$)|(\.log[.\d]) # matches the filename
value: .* …
```
=> Remove trailing whitespaces in configuration

.github/workflows/build.yml, .github/workflows/update_latest.yml
Fix GitHub Actions warning:
```
Warning: The `save-state` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Ref: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
Action Required:
- updating the GitHub runner software version used in self-hosted runners is necessary, because on self-hosted runners are we missing the `GITHUB_OUTPUT` environment file commands
- The version used by the self-hosted runners is 2.287.1
- The version containing support for `GITHUB_OUTPUT` is [2.297.0 ](https://github.com/actions/runner/releases/tag/v2.297.0)
=> (#1133) Replace action step `set output` with $GITHUB_OUTPUT

src/fn.c, src/wrap.c
"glibc provides no wrapper for io_getevents(), necessitating
the use of syscall(2)."
Ref: https://man7.org/linux/man-pages/man2/io_getevents.2.html
Closes #1186
TODO:
=> (#1186) Modify `io_getevents` to use `syscall`

cli/start/start.go, cli/util/util.go
- change file permissions after copying a `scope` from `0644` to `0755`
Closes: #1190
=> (#1190) Add executable permissions to `scope`

cli/start/start.go, cli/util/namespace.go, src/loaderop.c, src/loaderop.h, src/nsfile.c, src/nsfile.h, src/scope_static.c, src/scopestdlib.c, src/scopestdlib.h
- `conmon` is used as a parent process
to find all child processses for root and
rootless containers
E.g.
```
systemd(1)───systemd(4964)───conmon(2382451)───redis-server(2382454)
```
Closes: https://github.com/criblio/appscope/issues/1216
=> Add Podman container support - issue 1216

website/src/pages/docs/requirements.md
reasons for the change...
- we support a variety of runtime environments, some of which are excluded from the current description. it's easier for us to say which ones we don't support.
- there was duplication in talking about instrumenting static apps
=> Update requirements for using appscope

src/state.c
This PR contains a potential fix for race conditions caused by separate threads closing a connection while it's still in use. With this change, in our interposition of network close functions, instead of zero'ing out the net object, we only set the active bit to 0. We zero it out on open to reset the state for re-use. This allows for properties of the net object to be consumed safely until the net object is re-used.
Note: If we provide this as a test candidate to fix issues experienced with a v1.1.0 build - we should tag/release it right from this branch which was based on v1.1.0.
Note: Following the change, we manually checked code to see if the `net_info_t.active` field is respected throughout the code base. We determined that the first commit is probably all we need on this branch. The …
=> Potential fix for potential race condition caused in doClose

src/cfgutils.c
- remove `destroyEntry` to avoid memory corruption
- the protocol entry `found` which was in `g_protlist` was already freed by calling `lstDelete(g_protlist, key)` by `list->delete_fn`
Fixes: #1251
=> (#1251) Fix double free of `found` structure `destroyEntry`

cli/ipc/mq.go
(#1263) Fix using the unsafe and struct in msgQCurrentMessages
- use unsafe.Pointer with address of structure not the pointer
Ref: https://blog.gopheracademy.com/advent-2017/unsafe-pointer-and-system-calls/
Closes: #1263
=> (#1263) Fix msgQCurrentMessages segfault with syscall

src/cfgutils.c, src/ctl.c, src/ns.c, src/scopestdlib.h, src/setup.c, src/signalhandler.c, src/utils.c, src/utils.h, test/integration/glibc/scope-test, test/integration/musl/scope-test, test/utilstest.c
Example:
Executed process:
```
SCOPE_ERROR_SIGNAL_HANDLER=true ldscope -- ./fault_test 0
```
Output:
```
Scope Version: v1.2.2-194-gaf9dd47d8fec
Unix Time: 1674643542 sec
PID: 13
Process name: fault_test
!scopeSignalHandlerBacktrace signal 11 errno 0 fault address 0x55dbbadfa004, reason of fault:
Invalid permissions for mapped object
--- scopeLogBacktrace
#0 0x7f34dc632ebf scopeSignalHandlerBacktrace + 1226
#1 0x7f34dc333420 ?
#2 0x55dbbadf9220 read_only_area_error + 23
#3 0x55dbbadf935a test_function + 62
#4 0x55dbbadf93c5 main + 64
#5 0x7f34dc36c083 __libc_start_main + 243
#6 0x55dbbadf914e _start + 46
```
=> (#1287) Improve trace crash

src/scopetypes.h, src/signalhandler.c, src/signalhandler.h, src/wrap.c, test/integration/glibc/scope-test, test/integration/musl/scope-test
This Pull request required merging the following Pull Requests:
In this Pull Request following changes are introduced:
- extending the possible values of `SCOPE_ERROR_SIGNAL_HANDLER`
- generates the coredump in signal handler based on `coredump` or `full` value
- core dump will be generated in `/tmp/scope_core.<PID>` path
=> [#1279 4/4] Generate core dump in libscope.so

os/linux/Makefile, test/unit/library/test.c
- the instrumentation provided by `gcc`/`clang` compilers to use memory leak sanitizer
- to build library unit test instrumented with leak sanitizer:
```
make FSAN=1 libtest
```
=> (#1285) Add mechanism to detect memory leaks

src/ipc.c, src/ipc_resp.c, test/unit/library/ipctest.c
- Replace `cJSON_free` with proper destroy method
of CJSON object -> `CJSON_Delete`
- Avoid double free in case of structure already
added to root object - there is no need to
priv structure anymore
- Add missing `scope_free` for `cJSON_PrintUnformatted` method
Detected using memory sanitizer method from #1300
=> (#1108) Fix memory leaks in IPC

contrib/coredumper/configure.ac, contrib/coredumper/src/elfcore.c, install_build_tools.sh, os/linux/Makefile
Coredumper code does not used anything from `sys/sysctl.h` support
so it should be removed. The inclusion of a `sys/sysctl.h` generates
following warning on Ubuntu 20.04
```
"The <sys/sysctl.h> header is deprecated and will be removed.
```
On more modern OSes like Ubuntu 22.04 the warning mentioned above is
actually an error, since starting from glibc 2.32 the `sys/sysctl.h`
the header was removed.
Ref: https://abi-laboratory.pro/index.php?view=changelog&l=glibc&v=2.32
Other changes are not related to this PR but I found them during working on this issue
=> (#1302) Fix compilation coredumper on Ubuntu 22.04

cli/main.go, src/loader/loader.c, src/loader/loader.h, src/loader/ns.c, src/loader/ns.h, test/integration/cli/test_options.sh
This PR adds the capability for scope (in constructor mode) to act as a utility get a file from a namespace, and save it to a destination on the host's disk.
**Testing**
Integration tests were added to test the argument handling when file paths are passed as arguments to the new command `--getfile`.
Closes: #1312
=> Add ability to extract file from namespace 1312

os/linux/Makefile, os/linux/os.c, os/linux/os.h, os/macOS/os.c, os/macOS/os.h, src/scopeelf.c, src/wrap.c, src/wrap_go.c, test/unit/execute.sh, test/unit/library/ostest.c
```
Because of an AppScope bug, when you attached to a running Redis server process, the Redis server was restarting.
Here's how to verify that the bug is fixed.
sudo apt install redis -y
sudo systemctl status redis
grep MemoryDenyWriteExecute /lib/systemd/system/redis-server.service
watch -n 1 pgrep redis
sudo scope attach redis
redis-cli
set foo bar
sudo journalctl -u redis-server.service
<user_name> systemd[1]: redis-server.service: Main process exited, code=dumped, status=11/SEGV
<user_name> systemd[1]: redis-server.service: Failed with result 'core-dump'.
=> Funchook install fail 1293

cli/cmd/attach.go, cli/cmd/run.go, cli/cmd/util.go, cli/run/run.go, cli/run/scopeconfig.go
This PR adds the `--backtrace` and `--coredump` flags to `scope run` and `scope attach` that will update the cli-generated configuration for libscope.
```
scope run --help
scope run -d -b top
```
Closes #1319
=> Add coredump and backtrace flags 1319

conf/scope.yml
This PR clears out obsolete terminology from scope.yml, and makes capitalization and wording patterns consistent. It also adds explanations where there were bare headings (e.g., for the crash analysis section).
Working with @jrcheli , the old pattern of speaking of "backends" that use transports has been replaced by the idea of "features" that use transports. So we speak of a metrics feature, an events feature, etc.
Let's see how this all works for the team.
=> 1340 update scope.yml

cli/cmd/daemon.go, cli/cmd/inspect.go, cli/cmd/stop.go, cli/cmd/update.go, cli/update/update.go, cli/util/proc.go, src/snapshot.c, src/wrap.c
Following Pull Request addresss:
- https://github.com/criblio/appscope/issues/1250#issuecomment-1431440170
- fix typos discovered in code
- provide `scope daemon --filedest` example 
- remove unnecessary newline in `snapInfo` function
- remove unnecessary `fmt.Sprintf` in `getStopUsage` function
=> Minor issues with IPC 1250 & typos

src/wrap_go.c
```
scope_sprintf(g_ReadFrame_addr, "%p\n", ReadFrame_addr);
```
`scope_sprintf` will return 16 characters printed, while the size of `g_ReadFrame_addr` is 8 bytes `(sizeof(void*))`.
Side effect of the above is that without checking the return value and size limiation we will overwrite the value stored in `g_cfg.funcs_attached`.
Closes: #1354
=> Fix overwrite value on stack `g_cfg.funcs_attached` - 1354

Makefile, cli/cmd/k8s.go, cli/internal/version.go, cli/k8s/configs.go, cli/k8s/webhook.go
- `newrelic/k8s-webhook-cert-manager` is archived project since June 2, 2021
- update reference to https://github.com/criblio/k8s-webhook-cert-manager which handles deprecated API[1]:
```
The certificates.k8s.io/v1beta1 API version of CertificateSigningRequest is no longer served as of v1.22.
```
[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/
Required:
=> Change `webhook-cert-manager` reference

cli/k8s/webhook.go
- use the same "imagePullPolicy" for `scope-pod-extract` as
for Application container
- this fix would allow to avoid `ImagePullBackOff` status for
Application pod in following scenario:
- step 1 we preload the application image into cluster
- step 2 we deploy `scope k8s`
- step 3 we deploy application container
- This commit will modify `scope-pod-extract` behavior
to use the image which was preloaded in step 1 instead of
pulling the image from non-existent location
Fixes: #1409
=> Modify `scope-pod-extract` initContainer (1409)

contrib/redefine_syms.lst, src/scopestdlib.c, test/unit/execute.sh, test/unit/library/glibcvertest.c, test/unit/verboten_sym.sh
- `secure_get_env` is not supported by musl version prior 1.1.24
=> Remove secure_getenv usage in openssl (1408)

cli/cmd/inspect.go, cli/cmd/util.go, cli/inspect/inspect.go, cli/run/attach.go, cli/util/util.go, test/integration/cli/test_inspect.sh, website/src/pages/docs/cli-reference.md
This PR:
- adds a `--all` argument to retrieve status of all scoped processes
- in the case of multiple procs, the result will be a ndjson array of responses
- displays a helper menu when run without an argument
- ensures that successful output goes to stdout, all warnings and errors go to stderr
**Testing**
An integration test has been added to check that multiple scoped apps produce an array of results with the expected length.
**Documentation**
The cli-reference.md page has been updated accorgingly.
**QA**
Test the `scope inspect` command and its arguments ; when run as root/non-root ; on root/non-root procs.
Note: the `-j` flag currently has no implication, since output is already in json format.
=> Update the `inspect` cli command

cli/inspect/inspect.go, cli/ipc/ipcscope.go, src/ipc.c, src/ipc_resp.c, src/ipc_resp.h, test/manual/ipcclient.c
- provide information about pid, UUID, id and machine_id
Example  inspect output See process section:
```
{
"cfg": {
"current": {
"cribl": {
"enable": "false",
"transport": {
"type": "edge",
"tls": {
"enable": "",
"validateserver": "",
"cacertpath": ""
}
},
"authtoken": ""
},
"metric": {
"enable": "true",
"format": {
"type": "ndjson",
"statsdmaxlen": 512,
"verbosity": 4
},
"transport": {
"type": "file",
"path": "/home/foouser/.scope/history/htop_41_388986_1681742511594174848/metrics.json",
"buffering": "line",
"tls": {
"enable": "",
"validateserver": "",
"cacertpath": ""
}
},
"watch": [
{
"type": "fs"
},
{
"type": "net"
},
{
"type": "http"
},
{
"type": "dns"
},
{
"type": "process"
},
{
"type": "statsd"
}
]
},
"event": {
"enable": "true",
"format": {
"type": "ndjson"
},
"transport": { …
```
=> Extend IPC with details about process (#1415) 

src/wrap.c
This resolves an issue where, processes that do nothing in musl do not start the periodic thread - therefore interaction with scope ps, scope inspect, scope update is not possible.
=> Always start periodic thread in musl environments

cli/cmd/k8s.go, cli/k8s/configs.go, cli/k8s/template.go, website/src/pages/docs/cli-reference.md
- enable by default
- add option to disable it (`noprom`)
- add option to specify Prometheus exporter listening on port (`promport`)
Fixes #1419
=> Add k8s support for scope prometheus exporter (#1419)

src/mtcformat.c, test/integration/metriccapture/scope-test, test/unit/library/mtcformattest.c
Resolves #1397.
This makes some additional changes to prometheus format work that was originally done on the [feature/1397-prometheus-fmt](https://github.com/criblio/appscope/tree/feature/1397-prometheus-fmt) branch and merged into the [feature/prom-server-1398](https://github.com/criblio/appscope/tree/feature/prom-server-1398) branch by PR #1427.
=> Generate prometheus format from libscope.so, part two

cli/cmd/k8s.go, cli/k8s/configs.go, cli/k8s/template.go, website/src/pages/docs/cli-reference.md
- update used ` cribl/k8s-webhook-cert-manager`image 
- provide support for signername parameter in `scope k8s` command
=> Sync with webhook cert manager changes (#1434)

cli/events/events.go, cli/run/scopeconfig.go, cli/run/setup_test.go, test/integration/cli/expected.yml, test/integration/cli/test_cli_dest.sh
**This PR**
- Enables the process start event in the default scope cli config
- Ensures that process start events are redacted in the `scope events` output
**Testing**
- Unit and integration tests have been updated to ensure that expected configs match the new default output.
**Documentation**
n/a
**QA Instructions**
- Review the code
- Test the `scope events` command
Closes: #1451
=> Enable process start event by default in the cli (#1451)

contrib/funchook/CMakeLists.txt
- this commit will fix following warning:
```
CMake Warning:
Manually-specified variables were not used by the project:
CAPSTONE_BUILD_SHARED
```
See c8172e4 in capstone upstream repository for details
Fixes 1420
=> Capstone project rename build option: `CAPSTONE_BUILD_SHARED` -> `BUILD_SHARED_LIBS` (#1420)

cli/cmd/inspect.go, cli/cmd/update.go, cli/cmd/util.go, cli/update/update.go, test/integration/cli/Dockerfile, test/integration/cli/test_cli.sh, test/integration/cli/update_log_dest.yml, website/src/pages/docs/cli-reference.md
This PR:
- Extends the `scope update` command to accept a config file from StdIn
- Adds a `--fetch` argument to the `scope update` command. When provided, the process will be inspected after the config change.
- Ensures that successful output goes to stdout, all warnings and errors go to stderr
**Testing**
- An integration test has been added that passes a valid/invalid config to StdIn ; and another that passes it to `--config`
**Documentation**
- The website's `cli-reference.md` page has been updated accordingly.
- The cli's help menu has been updated with examples where appropriate.
**QA Instructions**
- Review the code
- Test the `scope update` command and its arguments.
=> Extend the `scope update` command (#1414)

cli/cmd/inspect.go, cli/cmd/update.go, website/src/pages/docs/cli-reference.md
**This PR**
When the `--json` argument is provided to `scope inspect` or `scope inspect --all`:
1) Don't pretty the json output
2) In the case of `--all`, render ndjson output, instead of an array of json objects
The `scope update` command has also been updated in the case that the `--fetch` argument was supplied.
**Testing**
No additional tests were added. QA instructions should suffice for this change.
**Documentation**
The CLI reference page has been updated to reflect new behavior.
**QA**
Try:
```
scope inspect
scope inspect --json
scope inspect <pid> --json | jq
scope inspect --all
scope inspect --all --json
scope inspect --all --json | jq
scope update <pid> --config ./conf/scope.yml --fetch --json
scope update <pid> --config ./conf/scope.yml --fetch --json | jq
```
=> `scope update` json fixes

src/javaagent.c, test/integration/docker-compose.yml, test/integration/jetty/Dockerfile, test/integration/jetty/scope-test
- Do not call `GetPrimitiveArrayCritical` on buffer address
- Perform explicitly memory allocation & copy
=> Handle `BufferAddr` in Java Agent

cli/k8s/configs.go
- allows to access `/metrics` endpoint
QA instructions:
```
#checkout to this branch
make build CMD="make all"
make image
kind create cluster
kind load docker-image cribl/scope:dev
docker run -it cribl/scope:dev scope k8s --metricdest tcp://scope-prom-export:9109 --metricformat prometheus --eventdest tcp://other.host:10070 --debug | kubectl apply -f -
kubectl run mycurlpod --image=curlimages/curl -i --tty -- sh
curl scope-prom-export:9090/metrics -v
```
=> Extend `scope prom` service with metrics port

cli/cmd/attach.go, cli/cmd/detach.go, cli/cmd/inspect.go, cli/cmd/ps.go, cli/cmd/start.go, cli/cmd/update.go, cli/run/attach.go, cli/run/run.go, cli/stop/stop.go, cli/util/namespace.go, cli/util/proc.go, cli/util/proc_test.go, cli/util/scopestate.go, test/integration/cli/test_cli.sh, website/src/pages/docs/cli-reference.md
**This PR**
Extends the cli `utils` package to read the proc directory of a foreign namespace, through the use of a `rootdir` prefix passed on the command line. As a result:
- The `inspect` command now allows container to host/container inspect.
- The `ps` command now supports a `--rootdir` argument to show processes on a host, or sibling container.
- The `inspect` command and the `detach` command now show a helper menu when no argument is provided, to allow the user to choose a process. When the `--rootdir` argument is provided, the helper menu displays scoped processes in the namespace related to the rootdir.
**Testing**
The CLI `proc_utils.go` unit test was updated.
No container-to-host or container-to-container integration tests have been added as it is not yet supported in our test …
=> Rootdir support in proc utils (#1414)

src/loader/attach.c, src/loader/ns.c, test/integration/node/Dockerfile.glibc
- print the `exe_path` before freeing it to avoid accessing memory after freeing
- free the `execArgv` array before returning from function
=> nit: issues founded by static analyzer & failing integration node test

cli/cmd/detach.go, cli/run/attach.go
Ensure that the attach/detach command always runs as a subprocess (instead of fork/exec), so we can control what happens with stdout and stderr. In this case, we want to ensure that all messages sent to the console are sent to stderr.
=> run attach as subprocess

cli/cmd/attach.go, cli/cmd/detach.go, cli/filter/filter.go, cli/run/attach.go, website/src/pages/docs/cli-reference.md
When `detach --wait` is used, wait 11 seconds for the detach to take place.
When `attach --inspect` is used, wait 10 seconds (plus 2) if we are doing a reattach.
=> Wait for detach and reattach to complete with certain flags

cli/cmd/attach.go, cli/cmd/detach.go, cli/cmd/inspect.go, cli/cmd/rules.go
Commands like `attach`, `detach`, `inspect`, `update`, `rules` should not emit anything other than json to stdout when the --json flag is supplied.
Some of these cobra commands were defined as functions that returned an error. That error is printed to stdout.
In some error cases those command functions would return non-nil values, and thus the error would be printed to stdout.
This PR changes those commands to not return any value. In the case when an error should be printed, the `util.ErrAndExit` function is now used, which emits errors to stderr and exits.
=> Print cli command errors to stderr instead of stdout

src/wrap.c
-  destroy cfg in case process rule status is equal RULES_NOT_SCOPED
=> `getScopeExec` destroy cfg

cli/util/newlinereader.go
When some of the CLI commands read in events, we see the error `error reading events: bufio.Scanner: token too long`. I increased the buffer size for the scanner to 1mb which seems more than appropriate for a single event. This resolves the issue in cases that I tested (events, flows).
Fixes #201
=> Set a larger (1mb) buffer size for each event in cli reader (#201)

contrib/Makefile
- avoid OOM during compilation on e.g. machine with 2 CPU(s), 2GB memory and disabled swap
```
gcc  -I. -Iinclude -Iproviders/common/include -Iproviders/implementations/include
-I../../openssl -I../../openssl/include -I../../openssl/providers/common/include
-I../../openssl/providers/implementations/include  -DECP_NISTZ256_ASM -DKECCAK1600_ASM
-DOPENSSL_BN_ASM_MONT -DOPENSSL_CPUID_OBJ -DPOLY1305_ASM -DSHA1_ASM -DSHA256_ASM
-DSHA512_ASM -DVPAES_ASM -fPIC -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE
-DOPENSSL_PIC -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-3\""
-DMODULESDIR="\"/usr/local/lib/ossl-modules\"" -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
-MMD -MF crypto/dso/libcrypto-lib-dso_win32.d.tmp -MT crypto/dso/libcrypto-lib-dso_win32.o -c
-o …
```
=> RFC nit: Fix Openssl compilation on machine with limited resources
