criblio/appscope

- cli/Makefile
- install_build_tools.sh
Don't mean to be fighting you with these changes, but our build doesn't work without them, and I'm trying to make it so your build and ours will *both* work.
Resolves #46
> (46) Fix the build again.  Use externally defined GOPATH if provided.

- test/testContainers/kafka/Dockerfile
> Use Kafka version 2.7.0

- website/src/components/Footer.js
- website/src/components/criblSiteNav/index.js
- website/src/components/layouts/documentationLayout.js
- website/src/data/corpSiteNav.yaml
- website/src/data/readyGetStarted.yaml
- website/src/scss/global.scss
Made requested changes per Jira tickets.
> Upfdates to layout items per Jira tickets

- website/src/data/documentationNav.yaml
- website/src/pages/documentation/cli-reference.md
- website/src/pages/documentation/config-files.md
- website/src/pages/documentation/examples-use-cases.md
- website/src/pages/documentation/how-works.md
- website/src/pages/documentation/library-using.md
- website/src/pages/documentation/loader-library.md
> Clean up typo's; reconcile left nav <–> page titles

- website/src/components/Highlights.js
- website/src/scss/_appScopeNav.scss
- website/src/scss/_criblNav.scss
- website/src/scss/_hero.scss
- website/src/scss/global.scss
Changed ordering of gif slices.
> Website last minute nits

- .github/workflows/website.yml
- cli/run/run_test.go
- cli/run/scopeconfig.go
> i believe this resolves issue 25

- contrib/cJSON/Makefile
- os/linux/Makefile
> (96) Fix issue with json locale where commas break json parsing.

- src/com.c
- src/com.h
- src/evtformat.c
- src/fn.h
- src/httpagg.c
- src/httpstate.c
- src/javaagent.c
- src/javabci.c
- src/linklist.h
- src/log.c
- src/search.c
> (120) Fix build issue that horks all linux distros but ubuntu 18.

- website/src/pages/docs/installing.md
> Link Docs > Installing to Docker

- test/testContainers/docker-compose.override.yml
- test/testContainers/docker-compose.yml
- test/testContainers/java/Dockerfile
- test/testContainers/java/Dockerfile.oracle
- test/testContainers/java/test-ssl.sh
> (#150) Add coverage for go1.16.  Fix build issues for java tests.

- src/scopeelf.c
- src/scopeelf.h
- src/wrap_go.c
> WIP: make scope work with go stripped binaries

- src/report.c
> Added local IP address to the filename for payload data

- src/report.c
- src/state.c
> Payload path name with UNIX sockets

- src/mtcformat.c
- test/mtcformattest.c
> (221) Send custom fields (tags) in ndjson metrics.

- src/httpagg.c
- test/httpaggtest.c
> (224) Fix missing http metrics after latest reshaping effort.

- src/wrap_go.c
> Get Go 16 working again.

- src/wrap.c
resolves #238
resolves #239
resolves #240
> (238) Fix several payload issues in node by adding syscall(close).

- src/com.c
> Don't url encode args when outputting in ndjson.

- website/src/pages/docs/library-using.md
@mQkatz would like your feedback please.
> Add some more detail on how to use AppScope in AWS Lambda

- src/state.c
> doDupFile had oldfd and newfd reversed.

- src/com.c
- src/ctl.c
- src/wrap.c
> (#262) Fix a couple minor startup memory leaks.

- os/linux/Makefile
- os/macOS/Makefile
- src/bashmem.c
- src/bashmem.h
- src/cfgutils.c
- src/utils.c
- src/utils.h
- src/wrap.c
- src/wrap_go.c
- test/testContainers/bash/Dockerfile
- test/testContainers/bash/runbashmem.sh
- test/testContainers/bash/runbashnomem.sh
- test/testContainers/bash/test_bash.sh
- test/testContainers/buildrunall.sh
- test/testContainers/docker-compose.override.yml
- test/testContainers/docker-compose.yml
- test/testContainers/runall.sh
> (#265) In bash procs, replace thread-unsafe mem subsystem when needed.

- cli/cmd/dash.go
> Fix printing version in dash

- cli/cmd/logs.go
- cli/cmd/run.go
- cli/cmd/util.go
- cli/cmd/watch.go
- cli/history/sessions.go
- cli/run/run.go
- cli/run/run_test.go
- cli/run/scopeconfig.go
- cli/run/scopeconfig_test.go
- cli/util/util.go
- cli/util/util_test.go
> adding watch, and log commands and loglevel option

- src/cfgutils.c
- src/transport.c
- src/transport.h
- test/transporttest.c
> (#320) Clean up connections to avoid ports stuck in TIME_WAIT.

- src/javabci.c
- src/report.c
- doHttpHeader, javaReadClass methods
> Fix memory leaks

- cli/cmd/run.go
- cli/cmd/util.go
- Add an example to scope run that uses the cribldest
- Improve the description of the cribldest, eventdest, metricsdest parameters
> Improve help message in the Cli

- README.md
Add build status badge to the README.
> Add Build Status Badge

- src/transport.c
- src/transport.h
- src/wrap.c
- test/testContainers/docker-compose.override.yml
- test/testContainers/docker-compose.yml
- test/testContainers/transport/Dockerfile
- test/testContainers/transport/README.md
- test/testContainers/transport/cribl/inputs.yml
- test/testContainers/transport/cribl/outputs.yml
- test/testContainers/transport/cribl/pipelines/route.yml
- test/testContainers/transport/docker-entrypoint.sh
- test/testContainers/transport/scope-test
> Fix missing console events (observed when using tls).

- src/httpagg.c
- src/report.c
- test/httpaggtest.c
> Change metric type from counter to timer for http.client.duration and http.server.duration.

- src/httpagg.c
- test/testContainers/kafka/Dockerfile
> Replace dots with underscores in dimensions.

- src/report.c
- src/state.c
> Enable protocol detect events without raw events.

- src/fn.c
- src/fn.h
- src/javaagent.c
- src/utils.c
- src/utils.h
- src/wrap.c
> Provide bash procs with the correct config file 

- src/fn.h
- src/wrap.c
> (#472) Address curl hang when writing payload files to disk.

- src/report.c
- src/wrap.c
> Honor SCOPE_CONNECT_TIMEOUT_SECS when connecting to logstream

- .vscode/launch.json
- correct the path to libary - currently it points to sh wrapper
- distinguish targets for x86_64 and aarch64
> Cleanup launch.json Vscode

- src/ctl.c
- src/dbg.c
- src/evtformat.c
- src/mtcformat.c
- src/report.c
- src/wrap.c
- test/manual/tcpserver.go
> add timestamp to payload

- .github/workflows/build.yml
- src/transport.c
> Remove mutex to resolve hang with logstream spawning a git pull

- Makefile
- docker/base/Dockerfile
> add `make image` target

- src/ctl.c
- src/report.c
- src/state.c
- src/state.h
- src/state_private.h
- determine file descriptor content type once
Ref: https://github.com/criblio/appscope/pull/504#issuecomment-912670846
> Optimize detect binary data

- test/cfgutilstest.c
Just a quick test to demo and doc how YAML anchors are and are not supported by libyaml.
Closes #535
> add unit test for YAML anchors

- test/testContainers/kafka/Dockerfile
> fix kafka download url

- cli/Makefile
> upx compress x86 cli

- cli/cmd/service.go
- test/testContainers/service/scope-test.initd
- test/testContainers/service/scope-test.systemd
Copy/paste error in the code is fixed so it's getting created now.
Updated the integration test to check it.
> Another fix for `scope service`

- .github/workflows/website.yml
- website/deploy.sh
> publish website only for web* tags

- .github/workflows/build.yml
> (583) github expressions use tics, not quotes

- .github/workflows/build.yml
- allows manually trigger "Build & Test" GitHub Action
Reference:
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> Add workflow_dispatch event

- test/testContainers/README.md
nit: file was removed with 27dfba05
> Update README: remove info about docker-compose.privileged.yml

- os/linux/os.c
- src/bashmem.c
- src/cfgutils.c
- src/com.c
- src/ctl.c
- src/javaagent.c
- src/mtcformat.c
- src/report.c
- src/scopeelf.c
- src/state.c
- src/sysexec.c
- src/transport.c
- src/wrap.c
- src/wrap_go.c
- Use previously introduced macro's to simplify calls, e.g.:
scopeLog(CFG_LOG_ERROR, ...) with scopeLogError,
scopeLog(CFG_LOG_WARN, ...) with scopeLogWarn,
scopeLog(CFG_LOG_INFO, ...) with scopeLogInfo
Ref: 40b7d5f
> Update scopeLog occurrences

- .github/workflows/build.yml
- test/testContainers/docker-compose.x86_64.yml
> Add integration tests for java 15 through 17.

- src/state.c
> Fix noisy "could not locate libresolv" message.

- contrib/Makefile
> Resolve crash when process exits during tls connection

- src/wrap.c
Changed log level for messages out of load_func()
> load_func() log messages moved to debug level.

- website/src/pages/docs/downloading.md
Thanks to Ed Bailey and @pdugas for the idea and content!
> Where to run AppScope - explanation

- src/report.c
> http status text

- cli/run/scopeconfig.go
- cli/run/scopeconfig_test.go
- conf/scope.yml
- src/cfg.c
- src/cfgutils.c
- src/scopetypes.h
- src/transport.c
- src/transport.h
- test/cfgtest.c
- test/cfgutilstest.c
- test/integration/cli/Dockerfile
- test/integration/cli/scope-test
- test/integration/cli/test_edge.sh
- test/manual/fluentbit/services/nginx/config/scope.yml
- test/manual/payload/conf_1/scope.yml
- test/manual/payload/conf_2/scope.yml
- test/manual/payload/conf_3/scope.yml
- test/manual/send_event/conf_1/scope.yml
- test/transporttest.c
- website/src/pages/docs/config-file.md
> Extend transport type with edge variant (cribl edge)

- src/inject.c
- test/integration/docker-compose.x86_64.yml
- test/integration/docker-compose.yml
- website/src/pages/docs/cli-using.md
> Add ARM support for attach

- src/report.c
Resolves #733 .
This is one small piece of #723.
> Metric consistency across verbosity settings

- src/evtformat.c
- src/httpagg.c
- src/mtcformat.c
- src/report.c
- src/wrap.c
resolves #740.
This implements on small part of #723.
> In low metric verbosity, make "summary" consistent.

- src/report.c
> Don't report aggregated and non-aggregated fs.error at the same time

- src/wrap.c
> fix crash observed in musl on (alpine distro)

- test/integration/musl/Dockerfile
- test/integration/musl/scope-test
- test/integration/musl/tcpserver.c
resolves #768 , prevents potential recurrence of #761.
> Create tls integration test on musl 

- src/javaagent.c
> Resolve segfault in Java

- src/evtformat.c
> In events make custom tags appear in body (don't duplicate in data)

- test/manual/schema/README_EVENTS.md
- test/manual/schema/README_METRICS.md
- test/manual/schema/README_OTHER.md
- test/manual/schema/extract.sh
- test/manual/schema/onemtc.sh
- test/manual/schema/onemtc2.sh
- test/manual/seqpacket/client.c
- test/manual/seqpacket/connection.h
- test/manual/seqpacket/server.c
> Capture json example steps - manual part (continue of #753)

- docker/docs/Dockerfile
- docker/docs/entrypoint.sh
- docker/docs/schema2md.js
- website/gatsby-config.js
- website/src/data/documentationNav.yaml
- website/src/pages/docs/schema-reference.md
- website/src/scss/_documentation.scss
- website/src/scss/global.scss
A script that generates an .md file from the JSON schema files.
This PR also includes some basic styling for tables and adds the `schema-reference` to the website.
> Schema to md script

- .github/workflows/build.yml
- test/integration/logstream/Dockerfile
- test/integration/logstream/scope-test
> invalidate the aws cdn cache for /dl/scope/latest too.

- website/src/pages/docs/changelog.md
- website/src/pages/docs/config-file.md
- website/src/pages/docs/schema-reference.md
- website/src/pages/docs/updating.md
This PR is my best guess at the docs changes needed for 1.0.1. Thanks, @michalbiesek and @iapaddler , for helping me get the details right.
There is also a commit which fixes a typo in the config file comments.
> update for 1.0.1

- src/httpstate.c
- src/httpstate.h
- src/report.c
- src/state.c
- src/state_private.h
- test/httpstatetest.c
> Separate http1 rx and tx state machines to support pipelining.

- docs/schemas/definitions/data.schema.json
- src/fn.c
- src/fn.h
- src/wrap.c
> Fix tail -f issue seen on RHEL 8.5.  Add missing _chk functions

- cli/cmd/attach.go
- cli/cmd/completion.go
- cli/cmd/dash.go
- cli/cmd/flows.go
- cli/cmd/history.go
- cli/cmd/metrics.go
- cli/cmd/ps.go
- cli/cmd/run.go
Self explanatory
Closes https://github.com/criblio/appscope/issues/611
QA Instructions https://github.com/criblio/appscope/issues/611
> Disallow mutually exclusive flags 611

- cli/cmd/flows.go
- cli/events/events_test.go
> Allow a user to specify an id and in/out id with scope flows #839

- docker/docs/Dockerfile
- docker/docs/layout.js
- docker/docs/schema2md.js
- docs/schemas/definitions/body.schema.json
- docs/schemas/definitions/data.schema.json
- docs/schemas/definitions/envelope.schema.json
- docs/schemas/event_console.schema.json
- docs/schemas/event_file.schema.json
- docs/schemas/metric_http_req.schema.json
> Update to schema2md script

- src/ctl.c
- src/scopetypes.h
- src/wrap.c
- test/ctltest.c
- test/integration/console/Dockerfile
- test/integration/console/httpd.conf
- test/integration/console/scope-test
> Make binary determination of console data an ongoing thing

- website/src/pages/docs/community.md
Please merge by 4/26/22, when the new "Cribl Curious" Q&A site launches to facilitate peer support across Cribl apps. Thanks!
> [Merge on 4/26/22] CRIBL-9216: Community page ++Q&A & Community-page links

- src/cfgutils.c
- test/integration/transport/Dockerfile
- test/integration/transport/scope-test
> Don't create a second CRIBL connection unless payloads are on

- website/src/pages/docs/requirements.md
Thanks, @seanvaleo , for sending over the content!
> docs / update 1 and add 3 lines

- src/evtformat.c
- src/mtcformat.c
- src/scope.c
- src/wrap.c
- `applciation` -> `application`
- `interate` -> `iterate`
- `precidence` -> `precedence`
> Fix typos in `src`

- website/src/pages/docs/how-works.md
- website/src/pages/docs/schema-reference.md
- website/src/pages/docs/updating.md
- website/src/pages/docs/what-do-with-scope.md
- website/src/pages/docs/working-with.md
This is a first attempt to explain basics of events and metrics, to give some context for the Schema Reference. 
The natural place to talk about this seemed to be on the Working with AppScope page — please let me know if you disagree.
This is the best I could do with the information I had handy, but:
- There may be inaccuracies.
- I'd like to add a few more examples.
- It might be good to talk about envelope and data in the schema structure. 
- Finally, @jrcheli pointed out some puzzling things about metric types. 
I'll follow up with the team on Thursday morning. Thanks all!
> say more about events and metrics

- src/gocontext.h
- src/wrap_go.c
- test/integration/go/Dockerfile
- test/integration/go/syscalls/unlinkatfalse.go
- test/integration/go/test_go.sh
Closes https://github.com/criblio/appscope/issues/933
> [GO] Handle return status from unlinkat 

- .github/workflows/schema.yml
- Makefile
- docker/docs/Dockerfile
- docker/docs/entrypoint.sh
- docker/docs/layout.js
- docs/schemas/README.md
- website/src/pages/docs/schema-reference.md
> Automatic schema in website generator #880

- test/integration/http/scope-test
- test/integration/syscalls/Dockerfile
- test/integration/syscalls/Dockerfile.alpine
- test/integration/syscalls/altp/tests/shutdown/shutdown_01.c
- test/integration/syscalls/ltp_p1.patch
- test/integration/syscalls/syscall_tests_conf.json
- test/integration/test_runner/app.py
- test/integration/test_runner/scope.py
- test/integration/tls/test_tls.sh
2 of 4 intermittent tests resolved.
> fixed intermittent tests for recvmsg01 & shutdown on Alpine

- conf/scope.yml
- src/state.c
- test/integration/http/conf_1/scope.yml
- test/manual/fluentbit/services/nginx/config/scope.yml
- test/manual/payload/conf_1/scope.yml
- test/manual/payload/conf_1/scope_protocol.yml
- test/manual/payload/conf_2/scope.yml
- test/manual/payload/conf_2/scope_protocol.yml
- test/manual/payload/conf_3/scope.yml
- test/manual/payload/conf_3/scope_protocol.yml
- test/manual/send_event/conf_1/scope_protocol.yml
- website/src/pages/docs/config-file.md
> Fix http1 detection race-condition in go.

- contrib/Makefile
- contrib/redefine_syms.lst
- src/scope.c
- src/scopestdlib.c
- src/scopestdlib.h
- test/integration/transport/Dockerfile
- test/integration/transport/plainClient.go
- test/integration/transport/scope-test
> Add test of static go that uses tls transport.

- cli/cmd/attach.go
- cli/cmd/completion.go
- cli/cmd/dash.go
- cli/cmd/events.go
- cli/cmd/excrete.go
- cli/cmd/flows.go
- cli/cmd/history.go
- cli/cmd/k8s.go
- cli/cmd/logs.go
- cli/cmd/metrics.go
- cli/cmd/prune.go
- cli/cmd/ps.go
- cli/cmd/run.go
- cli/cmd/service.go
- cli/cmd/util.go
- cli/cmd/version.go
- cli/cmd/watch.go
- conf/scope.yml
- website/src/pages/docs/cli-reference.md
- website/src/pages/docs/config-file.md
> Sync cli-reference.md with `scope help`

- conf/scope.yml
- website/src/pages/docs/config-file.md
- website/src/pages/docs/data-routing.md
This PR makes the changes @nicktank suggested in both the markdown version of the config file that lives in docs, and in the actual config file. It also removes a passage about a topic we'll address later.
> Docs/1015 tweak docs per PM

- test/integration/http/scope-test
> Fix failing http integration test

- .github/workflows/build.yml
resolves #964.  
This is a second pass for what was stared in #1023.
> Lambda zip file: Change root folder of zip from scope/ to lib/

- website/src/data/header.yaml
per request technical marketing
> Docs / new improved link to Cribl U

- test/integration/syscalls/Dockerfile.alpine
> [Backport to main branch] Fix `pip3 install virtualenv`

- cli/Makefile
- extend the building process with sanity check
of minimal required version of Go
- ref: d302293
> Add validation of required Go version

- .github/workflows/build.yml
- .github/workflows/update_latest.yml
Resolves #1003 
Updates latest here too: `docker pull cribl/scope:latest`
> Create new workflow to update https://cdn.cribl.io/dl/scope/latest

- cli/cmd/start.go
- cli/run/start.go
- cli/util/namespace.go
- test/integration/cli/Dockerfile
- test/integration/cli/test_cli.sh
- test/integration/start/scope-test
- website/src/pages/docs/cli-reference.md
- Provide a meaningful description of the scope start command as requested [here](https://github.com/criblio/appscope/pull/1049#discussion_r970893641)
- Closes https://github.com/criblio/appscope/issues/1105
- Handle the case where the docker daemon is not available
> Handle empty data in scope start

- cli/cmd/start.go
- cli/run/start.go
- src/cfgutils.c
- src/cfgutils.h
- src/scopetypes.h
- src/setup.c
- src/wrap.c
- test/cfgutilstest.c
- test/data/filter_0.yml
- test/data/filter_1.yml
- test/data/filter_2.yml
- test/data/filter_3.yml
- test/integration/start/scope-test
- website/src/pages/docs/cli-reference.md
- filter file should be defined in following locations: "/usr/lib/appscope/scope_filter" or "/tmp/scope_filter"
This Pull Request allows to handle the filter file in the `libscope.so`
Closes #1120
> Add handling filter file in the library layer

- cli/cmd/start.go
- cli/internal/version.go
- cli/loader/loader.go
- cli/start/start.go
- os/linux/Makefile
- src/libver.c
- src/libver.h
- src/ns.c
- src/ns.h
- src/scope_static.c
- src/scopestdlib.c
- src/scopestdlib.h
- src/setup.c
- test/execute.sh
- test/libvertest.c
- website/src/pages/docs/cli-reference.md
> Handle library paths

- os/linux/os.c
- os/linux/os.h
- src/inject.c
- src/inject.h
- src/scope.c
- src/scopetypes.h
- src/wrap.c
> Attach model updates

- src/libdir.c
- src/libdir.h
- src/loaderop.c
- src/scope_static.c
- test/libdirtest.c
- remove unnecessary passing version
- extend unit testing
> Libdir changes

- cli/cmd/start.go
- cli/loader/loader.go
- cli/start/start.go
- src/ns.c
- src/setup.c
- src/wrap.c
- website/src/pages/docs/cli-reference.md
- change tmp prefix for filter file
- rename `extractMemToChildNamespace` ->
- memset buffers before reuse
> Change tmp prefix for filter file

- cleanup_after_start.sh
- src/gocontext.S
- src/httpstate.c
- src/setup.c
- src/wrap.c
> [Dev] Add helper script to clear environment

- src/scope.c
- test/integration/attach/Dockerfile.glibc
- test/integration/attach/Dockerfile.musl
- test/integration/attach/dummy_filter
- test/integration/attach/scope_test_cfg.yml
- test/integration/attach/test_attach.sh
- test/integration/go/net/tlsClient.go
The current problem is how to handle `SCOPE_CONF_RELOAD` pointing to a file when the environment variables were previously set.
> Detach tests

- test/integration/start/scope-test
- handle rc, tc correctly
- use same logic as in `IsVersionDev` method
> Fix comparision in scope_start test

- cli/Makefile
- docker/builder/Dockerfile.ubuntu
- install_build_tools.sh
> Extend UPX support

- os/linux/os.c
- os/linux/os.h
- src/inject.c
- src/scope.c
> protect against mismatched libc on scope attach

- src/nsinfo.c
- src/scope.c
- test/libdirtest.c
Ref: https://github.com/criblio/appscope/pull/1194#issuecomment-1317364583
> Post fixes of 1181 comments

- src/nsinfo.c
- src/nsinfo.h
- src/scope_static.c
- test/nsinfotest.c
Ref: https://github.com/criblio/appscope/pull/1198#discussion_r1025383461
> Short function name `nsInfoIsPidGotNestedPidNs`

- src/ns.c
- src/scopetypes.h
- allows to setup scope start in host cron in case we have write access to the following mount points:
- `/etc/cron.d/`
- `/usr/lib/`
- `/tmp/` 
Above directories are requried to write a filtes there
Closes: #1199
> (#1199) Omit the namespace switch if hostfs is missing

- docker/builder/Dockerfile.ubuntu
- install_build_tools.sh
> (#1214) Bump UPX version from 4.0.0 to 4.0.1

- src/cfgutils.c
- test/cfgutilstest.c
- test/data/filter_0.yml
- test/data/filter_1.yml
- test/data/filter_4.yml
- test/data/filter_5.yml
- test/data/filter_6.yml
> In filter feature: allow _MatchAll_

- docs/CommandControl.md
resolves #1222
To see the markdown file rendered: https://github.com/criblio/appscope/blob/feature/1222-document-socket-interface/docs/CommandControl.md
> Create Command/Control markdown file.

- .github/workflows/build.yml
> Resolve caching issue of contrib projects with github actions

- website/src/pages/docs/changelog.md
> Docs/Changelog 1.2.2

- website/src/pages/docs/changelog.md
Here's a screenshot for reviewers:
> Docs – add security section to Changelog

- src/ipc.c
- test/ipctest.c
Ref https://github.com/criblio/appscope/pull/1219#issuecomment-1378558337
> IPC fixes related to post commit review of PR 1219

- src/backoff.h
- src/ipc.c
- src/ipc_resp.c
- src/libdir.c
- src/libver.c
- src/mtc.c
- src/mtcformat.c
- src/nsfile.c
- src/scopetypes.h
- src/strset.c
- src/strset.h
- src/transport.c
- test/httpaggtest.c
- test/httpheadertest.c
- test/httpstatetest.c
- test/manual/ipcclient.c
- test/manual/tcpclient.c
- test/manual/tcpserver.c
> bool and _GNU_SOURCE consistency

- docs/CommandControl.md
- src/cfgutils.c
- src/scopetypes.h
- src/transport.c
- src/transport.h
- test/cfgtest.c
- test/cfgutilstest.c
- test/ctltest.c
- test/logtest.c
- test/mtctest.c
- test/transporttest.c
> (#1271) Remove support for `syslog` and `shm`

- cli/ipc/ipcscope.go
- docs/IPC.md
- src/dbg.h
- src/ipc.c
- src/ipc.h
- src/ipc_resp.c
- src/ipc_resp.h
- test/ipctest.c
- test/manual/ipcclient.c
- retrieve supported cmd in IPC
- Logic is done in library and CLI - I am not sure where to put this in CLI
> (#1250) Extend IPC API supported cmds

- .github/workflows/build.yml
- .github/workflows/update_latest.yml
- .github/workflows/update_latest_release.yml
- .github/workflows/website.yml
this will eliminate the need for AWS keys to push scope binaries
> update appscope deploy to use oidc

- docs/ContribLibrary.md
> (#1281) Add short instruction about adding new contrib library

- docs/IPC.md
- docs/Namespace.md
- add info about namespaces
- add info how handle LXC, Docker container with AppScope
Notes:
- about effective uid/gid switch
- useful links
Closes: #1183
> Internal docs: namespace info 1183

- src/snapshot.c
- src/snapshot.h
- src/wrap.c
- test/integration/glibc/scope-test
- test/integration/java/test-ssl.sh
> Validate crashtrace and coredump with java app

- src/snapshot.c
- test/integration/java/test-ssl.sh
> Restore + improve the java_crash_analysis test

- src/loader/setup.c
- test/integration/start/scope-test
> Remove duplicate libscope.so entries when creating the profile script.

- cli/cmd/completion.go
- cli/cmd/prune.go
- website/src/pages/docs/cli-reference.md
This PR updates the CLI reference based on a help dump graciously provided by @jrcheli .
I've noted some questions below which I think will require a conversation with whoever is reviewing this.
> Docs/1341 update CLI reference

- src/gocontext.h
- src/wrap_go.c
- test/integration/docker-compose.x86_64.yml
> Remove support for go1.9 and go1.10

- test/manual/gosym/Dockerfile
- test/manual/gosym/README.md
- test/manual/gosym/cleanup.sh
- test/manual/gosym/gosym/gosym.c
- test/manual/gosym/gosym/gosymtest.go
- test/manual/gosym/gosym/test.sh
- test/manual/gosym/start.sh
- draft of environment for future Go support
> [RFC] Extend manual test with gosym environment

- cli/promserver/promserver.go
- test/integration/docker-compose.yml
- test/integration/prometheus/Dockerfile
- test/integration/prometheus/scope-test
- test/integration/prometheus/test_prom.sh
Initial set of tests
closes #1462
> Integration Tests for the Prom Exporter

- test/integration/attach/Dockerfile.musl
- test/integration/musl/Dockerfile
- test/integration/payload/Dockerfile.musl
- test/integration/start/Dockerfile.musl
- Alpine:latest points to 3.18
- see details in https://gitlab.alpinelinux.org/alpine/aports/-/issues/13017#note_181429
> Adjust `alpine:latest` based integration tests

- cli/k8s/webhook.go
> In the k8s server, ensure we don't mutate a pod more than once.

- cli/libscope/config.go
- cli/run/scopeconfig.go
> Add appscope prefix to prometheus metrics by default in the cli

- cli/cmd/promserver.go
- test/manual/k8s/exporter.txt
- adjust `port` name to `mport`
> Fix `scope prom` example

- cli/k8s/webhook.go
- avoid map assignment error in webhook
Fixes #1491
> Create label section in mutate when it is missing

- cli/k8s/configs.go
- test/manual/k8s/k8s.sh
> Add annotations to scope prometheus exporter for k8s discovery

- cli/run/scopeconfig.go
- cli/run/setup.go
- cli/run/setup_test.go
- src/loader/attach.c
- src/loader/loader.c
- src/loader/ns.c
- test/integration/cli/test_cli.sh
> Fix Attach issues 1508

- cli/cmd/extract.go
- cli/k8s/webhook.go
- test/manual/k8sdistroless/Dockerfile
- test/manual/k8sdistroless/README.md
- test/manual/k8sdistroless/deploy.yaml
- test/manual/k8sdistroless/main.c
- website/src/pages/docs/cli-reference.md
- Remove shell call from command as it may not be present in the desired pod
- Expand `scope extract` command to include support for creating directory
Fixes #1513
> Modified scope: init pod mechanism

- src/cfgutils.c
- src/cfgutils.h
- src/wrap.c
- test/data/filter/corrupted_filter.yml
- test/data/filter/empty_filter_1.yml
- test/data/filter/empty_filter_2.yml
- test/unit/library/cfgutilstest.c
- if filter file is empty treat it as it is missing
- if filter file does not have `allow` or `deny` entry treat it as it filter was missing
Fixes #1510
> [RFC] Check filter file if it is empty or corrupted (1510)

- os/linux/os.c
> Add close on exec when memfd is created

- cli/rules/rules.go
- src/cfgutils.c
- src/loader/ns.c
- src/loader/scopetypes.h
- src/loader/setup.c
- src/scopetypes.h
- src/wrap.c
> Remove support for tmp filter path (#1537)

- src/cfgutils.c
- test/unit/library/cfgutilstest.c
> Mount the socket dir, not the socket.

- cli/run/setup.go
> non-root process picks up config when attaching via `scope rules --add`

- src/wrap.c
- test/integration/attach/test_attach.sh
> Scope in path and ld.so.preload

- src/wrap.c
> Extend `doNotScopeList` with `snapd`

- src/loader/setup.c
**QA Instructions**
```
docker run --rm -it ubuntu
ps -ef | grep /bin/bash # note the pid
sudo ./bin/linux/x86_64/scope --mount <existing dir> --namespace <bash pid>
sudo ./bin/linux/x86_64/scope --mount <non-existent dir> --namespace <bash pid>
```
Closes #1603
> Check for mount dest presence on host (#1603)
